-- aftekenboek — de diploma's en hun eisen
--
-- This file is the catalogue. It is written to be run again, as often as you
-- like: every row upserts on its `code`, so ids stay the same and aftekeningen
-- that already exist keep pointing at the same eis. That is what makes it safe
-- to correct a typo, sharpen a toelichting or add a diploma and re-run the
-- whole file against a database that is already in use.
--
-- Source per diploma is in the `source` column and in docs/EISEN.md. Where the
-- handboek is ambiguous the list here is deliberately the longer one: an eis
-- too many is visible on screen and can be deleted, an eis that is missing is
-- invisible and gets forgotten.
--
-- Strings are dollar-quoted ($$...$$) throughout, so an apostrophe in
-- "Roeicommando's" needs no escaping and cannot silently break the file.
--
-- Run after 003-rpc.sql.

-- ---------------------------------------------------------------- disciplines

insert into disciplines (code, name, subtitle, sort_order) values
  ('roeien',   $$Roeien$$,            $$Roeivlet$$,               1),
  ('kielboot', $$Zeilen$$,            $$Kielboot$$,               2),
  ('bbm',      $$Buitenboordmotor$$,  $$Boot met buitenboordmotor$$, 3),
  ('sloep',    $$Sloep en motorvlet$$, $$Motorvaren$$,            4)
on conflict (code) do update set
  name       = excluded.name,
  subtitle   = excluded.subtitle,
  sort_order = excluded.sort_order;

-- ---------------------------------------------------------------- diploma's

insert into diplomas (discipline_id, code, name, level_label, summary, sort_order, source)
select d.id, v.code, v.name, v.level_label, v.summary, v.sort_order, v.source
from (values
  ('roeien', 'roeien-12', $$Roeien I/II$$, $$I/II$$,
   $$Voor wie onder niet te moeilijke omstandigheden op meren en plassen kan varen in een roeivlet: niet te druk vaarwater, overdag, met voldoende zicht.$$,
   1, $$Handboek Opleidingen deel 3.2 Roeien (2015), §3.2.4$$),

  ('roeien', 'roeien-3', $$Roeien III$$, $$III$$,
   $$Voor wie het commando kan voeren over een roeivlet met een groep roeiers, op meren, plassen en kanalen tot en met windkracht 5 Beaufort.$$,
   2, $$Handboek Opleidingen deel 3.2 Roeien (2015), §3.2.5$$),

  ('kielboot', 'kielboot-1', $$Kielboot I$$, $$I$$,
   $$Voor wie onder gunstige omstandigheden kan zeilen: rustig vaarwater en matige wind tot en met 3 Beaufort, in een boot van minstens 200 kg met maximaal 20 m² zeil.$$,
   1, $$Handboek Opleidingen deel 3.1 Kielboot (2015), §3.1.4$$),

  ('kielboot', 'kielboot-2', $$Kielboot II$$, $$II$$,
   $$Voor wie onder niet te moeilijke omstandigheden op meren en plassen kan zeilen, overdag en met voldoende zicht, tot en met windkracht 4 Beaufort.$$,
   2, $$Handboek Opleidingen deel 3.1 Kielboot (2015), §3.1.5$$),

  ('kielboot', 'kielboot-3', $$Kielboot III$$, $$III$$,
   $$Voor wie tot en met windkracht 6 zelfstandig kan varen op meren, plassen en kanalen, in een boot van minstens 200 kg met maximaal 30 m² zeil.$$,
   3, $$Handboek Opleidingen deel 3.1 Kielboot (2015), §3.1.6$$),

  ('kielboot', 'kielboot-4', $$Kielboot IV$$, $$IV$$,
   $$Voor wie onder alle omstandigheden kan varen. Alleen te halen met een examen onder toezicht van een erkend examinator, bij 7 tot 25 knopen wind. Gelijk aan het eigenvaardigheidsniveau van de Zeilinstructeur 3-opleiding.$$,
   4, $$Handboek Opleidingen deel 3.1 Kielboot (2015), §3.1.7$$),

  ('bbm', 'bbm-12', $$Buitenboordmotor I/II$$, $$I/II$$,
   $$Voor wie onder eenvoudige omstandigheden met een buitenboordmotor vaart: tot en met windkracht 3 Beaufort, bij daglicht, op meren en kanalen.$$,
   1, $$Handboek Opleidingen deel 3.3 Buitenboordmotor (2015), §3.3.4$$),

  ('bbm', 'bbm-3', $$Buitenboordmotor III$$, $$III$$,
   $$Voor wie tot en met windkracht 5 Beaufort zelfstandig vaart op meren en kanalen, vaarwater klasse 1 t/m 4.$$,
   2, $$Handboek Opleidingen deel 3.3 Buitenboordmotor (2015), §3.3.5$$),

  ('sloep', 'sloep-1', $$Bemanningslid$$, $$CWO I$$,
   $$Vanaf 12 jaar. Kan onder verantwoordelijkheid van de schipper als bemanningslid op een sloep of motorvlet meedraaien.$$,
   1, $$Handboek Opleidingen deel 3.4 Motorboot / Sloep- en motorvletvaren (2020), §2.1 en §4.1$$),

  ('sloep', 'sloep-2', $$Dagschipper$$, $$CWO II$$,
   $$Vanaf 16 jaar. Vaart, manoeuvreert en navigeert zelfstandig bij daglicht tot windkracht 4, en geeft daarbij leiding aan de bemanning.$$,
   2, $$Handboek Opleidingen deel 3.4 Motorboot / Sloep- en motorvletvaren (2020), §2.2 en §4.1$$),

  ('sloep', 'sloep-3', $$Schipper$$, $$CWO III$$,
   $$Vanaf 18 jaar. Vaart zelfstandig bij dag en nacht tot windkracht 6 en geeft onder alle omstandigheden leiding aan de bemanning. Eigenvaardigheidsniveau van Instructeur I-2.$$,
   3, $$Handboek Opleidingen deel 3.4 Motorboot / Sloep- en motorvletvaren (2020), §2.3 en §4.1$$),

  ('sloep', 'sloep-4', $$All Round Schipper$$, $$CWO IV$$,
   $$Vanaf 18 jaar. Draagt de eindverantwoordelijkheid voor bemanning en schip op meerdaagse tochten naar onbekende bestemmingen. Instapeis: een tochtplanning voor een door de examinator opgegeven tocht.$$,
   4, $$Handboek Opleidingen deel 3.4 Motorboot / Sloep- en motorvletvaren (2020), §2.4 en §4.1$$)
) as v(discipline, code, name, level_label, summary, sort_order, source)
join disciplines d on d.code = v.discipline
on conflict (code) do update set
  discipline_id = excluded.discipline_id,
  name          = excluded.name,
  level_label   = excluded.level_label,
  summary       = excluded.summary,
  sort_order    = excluded.sort_order,
  source        = excluded.source;

-- ---------------------------------------------------------------- de eisen
--
-- `position` is the number the eis carries in the handboek, so the lijst on
-- screen and het boekje in de hand tellen gelijk op.

insert into requirements (diploma_id, code, kind, position, title, detail)
select dp.id, v.code, v.kind::requirement_kind, v.position, v.title, v.detail
from (values

-- ---------------- Roeien I/II — praktijk
('roeien-12', 'roeien-12.p1',  'praktijk', 1, $$Het schip vaarklaar en nachtklaar maken$$,
 $$Inventaris controleren, schip schoon en droog maken. Riemen juist neerleggen: blad naar de boeg, wrikriem aan stuurboord met het blad naar de spiegel. Controleren op lek- en regenwater. Voor iedere opvarende een reddingvest aan boord, bij voorkeur aangetrokken.$$),
('roeien-12', 'roeien-12.p2',  'praktijk', 2, $$Verhalen van het schip$$,
 $$Zonder motor. Alle manieren op spierkracht mogen, zolang het geen gevaar oplevert voor bemanning, materiaal of andere scheepvaart. Op het schip zelf zo veel mogelijk vanuit de kuip werken.$$),
('roeien-12', 'roeien-12.p3',  'praktijk', 3, $$Roeicommando's uitvoeren$$,
 $$Op bevel van de schipper kunnen uitvoeren: dollen in; los voor en los achter; op riemen; haalt op gelijk; stopt af; strijkt gelijk; zet af; riemen lopen; riemen geroeid. De commando's kunnen vooraf worden gegaan door 'beide boorden', 'stuurboord' of 'bakboord'.$$),
('roeien-12', 'roeien-12.p4',  'praktijk', 4, $$Aanleg met de punt van het schip$$,
 $$In de wind aanleggen op een vooraf aangewezen punt, met roeicommando's, zó dat het schip zonder noemenswaardige kracht afgehouden kan worden. De instructeur mag aanwijzingen geven om het veilig te laten verlopen.$$),
('roeien-12', 'roeien-12.p5',  'praktijk', 5, $$Een acht varen$$,
 $$Zonder noemenswaardig roergebruik: twee rondjes in tegengestelde richting. De bochten worden gemaakt door de ene boord te laten halen en de andere te laten strijken.$$),
('roeien-12', 'roeien-12.p6',  'praktijk', 6, $$Jagen$$,
 $$Met een aantal mensen het schip aan een lijn vooruittrekken. De lijn vlak bij het draaipunt vastmaken, zodat de boeg niet naar de kant wordt getrokken, lang genoeg, en met gebruik van de driftbeperkende middelen. Let op de natuur en andermans spullen.$$),
('roeien-12', 'roeien-12.p7',  'praktijk', 7, $$Wrikken$$,
 $$Met één riem in het wrikgat het schip in een rechte lijn voortbewegen.$$),
('roeien-12', 'roeien-12.p8',  'praktijk', 8, $$Het schip afmeren$$,
 $$Zo vastleggen dat ook op lange termijn geen schade aan eigen of andere schepen mogelijk is. Zo min mogelijk lijnen naar de wal (minder dan 3 of meer dan 6 is altijd fout), zo lang mogelijk gekozen. Eerst de lijnen die de natuurlijke beweging van het schip tegengaan.$$),
('roeien-12', 'roeien-12.p9',  'praktijk', 9, $$Toepassing van de reglementen$$,
 $$De uitwijkregels voor het eigen vaargebied toepassen. Een uitwijkmanoeuvre wordt tijdig ingezet. De bemanning mag waarschuwen voor andere scheepvaart.$$),

-- ---------------- Roeien I/II — theorie
('roeien-12', 'roeien-12.t1',  'theorie', 1, $$Schiemanswerk$$,
 $$Bij naam kennen, kunnen leggen en de functie kennen van: twee halve steken (de eerste slippend), achtknoop, platte knoop, mastworp (met slipsteek als borg). Ook: een lijn opschieten en een lijn beleggen op een kikker.$$),
('roeien-12', 'roeien-12.t2',  'theorie', 2, $$Roeitermen$$,
 $$Kunnen aangeven wat bedoeld wordt met: slagroeier, boegroeier, midroeier, roerganger, haakvoor, stuurboord, bakboord, hogerwal, lagerwal, bomen, jagen, wrikken, in de wind, opschieten, beleggen. Plus alle roeicommando's.$$),
('roeien-12', 'roeien-12.t3',  'theorie', 3, $$Onderdelen$$,
 $$Van de eigen boot en tuigage, in de praktijk én op een tekening, minstens 15 onderdelen bij de juiste naam noemen. In ieder geval: boeg, hek, dolboord, doften, roer, helmstok, stuurboord en bakboord, roeiriem, wrikriem.$$),
('roeien-12', 'roeien-12.t4',  'theorie', 4, $$Veiligheid$$,
 $$De eisen kennen die aan een reddingvest gesteld worden. Weten hoe te handelen bij een omgeslagen boot.$$),
('roeien-12', 'roeien-12.t5',  'theorie', 5, $$Reglementen$$,
 $$De genoemde artikelen uit het Binnenvaartpolitiereglement kunnen toepassen: begripsbepalingen 1.01, voorzorgsmaatregelen 1.04, afwijking 1.05, tegengestelde koersen 6.01/6.03/6.04, voorbijlopen 6.10, vertrek 6.14, kruisende koersen 6.17, ligplaats innemen 7.01. Weten dat er naast het BPR andere reglementen gelden en waar die te vinden zijn.$$),
('roeien-12', 'roeien-12.t6',  'theorie', 6, $$Gedragsregels$$,
 $$De goede gebruiken kennen ten opzichte van andere watersporters, waaronder wedstrijdzeilers. De verantwoording kennen ten opzichte van het milieu.$$),
('roeien-12', 'roeien-12.t7',  'theorie', 7, $$Weersinvloeden$$,
 $$Het weerbericht kunnen interpreteren met het oog op de veiligheid en de eigen vaardigheid. Voortekenen van plotselinge weersomslagen, zoals onweer en zware windvlagen, tijdig herkennen.$$),
('roeien-12', 'roeien-12.t8',  'theorie', 8, $$Vaarproblematiek andersoortige schepen$$,
 $$Het gevaar kennen van de dode hoek en van de zuiging van grote schepen. Weten dat grote schepen op smal vaarwater niet kunnen wijken, en dat ook grote vrachtschepen sterk kunnen verlijeren.$$),

-- ---------------- Roeien III — praktijk
('roeien-3', 'roeien-3.p1',  'praktijk',  1, $$Het schip vaarklaar en nachtklaar maken$$,
 $$Inventaris controleren, schip schoon en droog. Riemen juist neerleggen: blad naar de boeg, wrikriem aan stuurboord met het blad naar de spiegel. Dollen uit de dolpotten, zwaard op, anker geborgd. Controleren op lek- en regenwater, en voor iedere opvarende een reddingvest aan boord.$$),
('roeien-3', 'roeien-3.p2',  'praktijk',  2, $$Verhalen van het schip$$,
 $$Over kleine afstanden, zonder motor én zonder roeiriemen. Het mag geen gevaar opleveren voor bemanning, materiaal of andere scheepvaart; op het schip zelf zo veel mogelijk vanuit de kuip werken.$$),
('roeien-3', 'roeien-3.p3',  'praktijk',  3, $$Roeitechnieken en roeicommando's kunnen uitvoeren$$,
 $$Boven op de commando's van Roeien I/II ook: riemen op, dollen richten, riemen toe, riemen over, stootwillen binnen en buiten. Op bevel van de schipper uitvoeren.$$),
('roeien-3', 'roeien-3.p4',  'praktijk',  4, $$Roeicommando's kunnen geven$$,
 $$Dezelfde commando's zelf op het juiste moment gebruiken, luid en duidelijk, met goed onderscheid tussen bakboord en stuurboord waar de manoeuvre dat vraagt.$$),
('roeien-3', 'roeien-3.p5',  'praktijk',  5, $$Aanleg met de punt van het schip$$,
 $$Met roeicommando's aanleggen op een vooraf aangewezen punt, boeg naar de wal, zó dat het schip zonder noemenswaardige kracht afgehouden kan worden.$$),
('roeien-3', 'roeien-3.p6',  'praktijk',  6, $$Aanleggen met de spiegel van het schip$$,
 $$Zelfde punt, maar met de spiegel naar de wal. Houd rekening met de afstand die je moet strijken, en bedien het roer zoals het bij een achteruitvarend schip hoort.$$),
('roeien-3', 'roeien-3.p7',  'praktijk',  7, $$Zijwaartse aanleg$$,
 $$Met de zijkant langs de wal, op een vooraf aangewezen punt, zonder noemenswaardige kracht af te hoeven houden. Stootwillen worden goed gebruikt.$$),
('roeien-3', 'roeien-3.p8',  'praktijk',  8, $$Een kleine acht varen$$,
 $$Zonder roergebruik, twee rondjes in tegengestelde richting. De bochten door de ene boord te laten halen en de andere te laten strijken of afstoppen — met inzicht in welke bocht welk commando oplevert.$$),
('roeien-3', 'roeien-3.p9',  'praktijk',  9, $$Man over boord manoeuvre$$,
 $$Constateren en roepen, "zwem" toeroepen, zo nodig een drijfmiddel toewerpen en iemand laten wijzen. Ruime bocht, aan de windse koers aankomen, langzaam aan lij langsvaren; riemen lopen aan loef, riemen aan lij in het water. De drenkeling aan loef op het draaipunt zijdelings en zo horizontaal mogelijk binnenhalen. Bij weinig wind kan strijken ook.$$),
('roeien-3', 'roeien-3.p10', 'praktijk', 10, $$Eenvoudig ankeren$$,
 $$Stilliggen bij het uitgooien, geen lijnen om het anker, het anker moet zich kunnen ingraven en het schip blijft nagenoeg in de wind liggen. Strijken tot het anker houdt, en controleren met een achtergrondspeiling.$$),
('roeien-3', 'roeien-3.p11', 'praktijk', 11, $$Roeimanoeuvres zonder roer$$,
 $$Enkele manoeuvres uitvoeren zonder het roer te gebruiken — bijvoorbeeld een kleine of een grote acht.$$),
('roeien-3', 'roeien-3.p12', 'praktijk', 12, $$Jagen$$,
 $$Het schip aan een lijn vooruittrekken, en verschillende manieren van jagen kennen. De lijn lang genoeg, de driftbeperkende middelen in gebruik. Let op de natuur en andermans spullen.$$),
('roeien-3', 'roeien-3.p13', 'praktijk', 13, $$Wrikken$$,
 $$Met één riem in het wrikgat het schip voortbewegen én ermee kunnen manoeuvreren, met aandacht voor de overige scheepvaart.$$),
('roeien-3', 'roeien-3.p14', 'praktijk', 14, $$Het schip afmeren$$,
 $$Zo vastleggen dat ook op lange termijn geen schade aan eigen of andere schepen mogelijk is. Minder dan 3 of meer dan 6 lijnen naar de wal is altijd fout; kies ze zo lang mogelijk en leg eerst de lijnen vast die de natuurlijke beweging van het schip tegengaan.$$),
('roeien-3', 'roeien-3.p15', 'praktijk', 15, $$Aanvarings- en achtergrondpeiling kunnen maken$$,
 $$Bij kruisende koersen vaststellen of er aanvaringsgevaar ontstaat, door over het andere schip een peiling op de achtergrond te nemen.$$),
('roeien-3', 'roeien-3.p16', 'praktijk', 16, $$Toepassing van de reglementen$$,
 $$De uitwijkregels voor het eigen vaargebied toepassen, en een uitwijkmanoeuvre tijdig inzetten.$$),
('roeien-3', 'roeien-3.p17', 'praktijk', 17, $$Terminologie$$,
 $$Zo veel mogelijk de juiste naamgeving gebruiken — binnen de boot én tussen schepen en personen onderling.$$),
('roeien-3', 'roeien-3.p18', 'praktijk', 18, $$Tonen van inzicht, veiligheid$$,
 $$De roerganger heeft kennis van zaken, bereidt zijn manoeuvres voor en stelt ze zo nodig bij. Hij kijkt goed om zich heen en houdt rekening met bemanning en omgeving.$$),
('roeien-3', 'roeien-3.p19', 'praktijk', 19, $$Schiemannen praktijk$$,
 $$Touwwerk vrij van zand en scherpe randen houden. Bij naam kennen, kunnen leggen en de functie kennen van: twee halve steken (de eerste slippend), achtknoop, platte knoop, mastworp (met slipsteek als borg), enkele schootsteek, paalsteek. Plus een lijn opschieten en beleggen op een kikker.$$),

-- ---------------- Roeien III — theorie
('roeien-3', 'roeien-3.t1', 'theorie', 1, $$Schiemanswerk$$,
 $$Dezelfde steken als in de praktijkeis, met hun functie, plus opschieten en beleggen. Ook: touwwerk vrij van zand houden en zo veel mogelijk uit UV-licht, en het begrip schavielen met de maatregelen daartegen kunnen beschrijven.$$),
('roeien-3', 'roeien-3.t2', 'theorie', 2, $$Roeitermen$$,
 $$Weten wat bedoeld wordt met: slagroeier, boegroeier, roerganger, haakvoor, stuurboord, bakboord, hogerwal, lagerwal, loef, lij, bomen, jagen, wrikken, in de wind, opschieten, beleggen. Plus alle commando's, inclusief die voor zwaard en anker.$$),
('roeien-3', 'roeien-3.t3', 'theorie', 3, $$Onderdelen$$,
 $$Van eigen boot en tuigage, in de praktijk en op een tekening, minstens 30 onderdelen bij naam noemen. In ieder geval: boeg, hek, spiegel, dolboord, doften, roer, helmstok, stuur- en bakboord, roeiriem, wrikriem, blad, handvat, dollen, dolpot, landvast, hoosvat.$$),
('roeien-3', 'roeien-3.t4', 'theorie', 4, $$Veiligheid$$,
 $$Weten hoe te handelen bij een omgeslagen boot. De eisen kennen die aan een zwemvest én aan een reddingvest gesteld worden, en weten hoe reddingvest en reddingsboei gebruikt moeten worden.$$),
('roeien-3', 'roeien-3.t5', 'theorie', 5, $$Reglementen$$,
 $$Een flink uitgebreidere lijst uit het Binnenvaartpolitiereglement dan bij Roeien I/II: begripsbepalingen, verplichtingen van de schipper, tekens en lichten van grote en kleine schepen, veerponten en drijvende werktuigen, geluidsseinen, verkeerstekens, de vaarregels, bruggen en sluizen. Ook weten welke andere reglementen in het eigen vaargebied gelden, waar je ze vindt, en dat voor bepaalde schepen een Klein Vaarbewijs verplicht is. De volledige artikelopsomming staat in het handboek.$$),
('roeien-3', 'roeien-3.t6', 'theorie', 6, $$Theorie van het roeien$$,
 $$Theoretische kennis van de verschillende manoeuvres, van de roerwerking achteruit en van de theorie achter het jagen. De functie van het midzwaard kennen, en weten om te gaan met stroom op een rivier.$$),
('roeien-3', 'roeien-3.t7', 'theorie', 7, $$Gedragsregels, vlagvoering en jachtetiquette$$,
 $$De goede gebruiken ten opzichte van andere watersporters kennen, en de verantwoording ten opzichte van het milieu.$$),
('roeien-3', 'roeien-3.t8', 'theorie', 8, $$Weersinvloeden$$,
 $$Het weerbericht kunnen interpreteren met het oog op de veiligheid en de eigen vaardigheid, en voortekenen van plotselinge weersomslagen zoals onweer en zware windvlagen tijdig herkennen.$$),
('roeien-3', 'roeien-3.t9', 'theorie', 9, $$Vaarproblematiek andersoortige schepen$$,
 $$Het gevaar kennen van de dode hoek en van de zuiging van grote schepen. Weten dat grote schepen op smal vaarwater niet kunnen wijken, en dat ook grote vrachtschepen sterk kunnen verlijeren.$$),

-- ---------------- Kielboot I — praktijk
('kielboot-1', 'kielboot-1.p1',  'praktijk',  1, $$Het schip zeilklaar en nachtklaar maken$$,
 $$Zeilklaar: zeilkleden eraf, kraanlijn doorzetten, mik of schaar weg, fok aanslaan, fokkenschoten inscheren, vallen aanslaan, inventaris controleren. Nachtklaar: vallen los en rammelvrij wegwerken, fok in de zak, grootzeil opdoeken, giek en gaffel op de mik, kraanlijn los, zeilkleden erop, inventaris opruimen.$$),
('kielboot-1', 'kielboot-1.p2',  'praktijk',  2, $$Verhalen van het schip$$,
 $$Zonder motor. Alle manieren op spierkracht mogen, zolang het geen gevaar oplevert voor bemanning, materiaal of andere scheepvaart. Op het schip zelf zo veel mogelijk vanuit de kuip werken.$$),
('kielboot-1', 'kielboot-1.p3',  'praktijk',  3, $$Stilliggend hijsen en strijken van de zeilen$$,
 $$Met de kop nagenoeg in de wind, zo nodig eerst verhalen, en iemand zorgt dat het schip niet tegen de wal komt. Grootzeil: schoot los, zeilbandjes los, bij gaffelzeil de gaffel op circa 45 graden, vallen samen, klauwval vast, halstalie vast, piek stellen tot er een plooi van nok naar hals staat. Fok: schoothoek lostrekken, strietsen, val beleggen, vallen en kraanlijn opschieten.$$),
('kielboot-1', 'kielboot-1.p4',  'praktijk',  4, $$Stand en bediening van de zeilen$$,
 $$Op een rechte koers én in de bocht zo veel mogelijk de juiste zeilstand. Zeilen zo ver gevierd als kan zonder dat het voorlijk kilt; bij oploeven mag de fok, bij afvallen het grootzeil bescheiden killen. De zeilen ondersteunen het sturen.$$),
('kielboot-1', 'kielboot-1.p5',  'praktijk',  5, $$Sturen, roer- en schootbediening$$,
 $$Met roer en zeilen een rechte koers en bochten varen, zó dat een aangewezen punt zonder onnodige omwegen wordt aangezeild.$$),
('kielboot-1', 'kielboot-1.p6',  'praktijk',  6, $$Overstag gaan$$,
 $$Van hoog aan de wind over de ene boeg naar hoog aan de wind over de andere. Commando's: "klaar om te wenden" als waarschuwing, "ree" bij de start (fokkenschoot 10 à 15 cm vieren), zo nodig "fok bak", "fok over" zodra de boot door de wind is, "fok aan" als er weer snelheid is. Zo min mogelijk roer; de stuurman gaat met het gezicht naar voren verzitten.$$),
('kielboot-1', 'kielboot-1.p7',  'praktijk',  7, $$Opkruisen in breed vaarwater$$,
 $$Goed hoog aan de wind varen en zo nodig overstag gaan om een in de wind gelegen punt aan te zeilen.$$),
('kielboot-1', 'kielboot-1.p8',  'praktijk',  8, $$Gijpen$$,
 $$Zien aankomen dat er gegijpt moet worden en de bemanning waarschuwen. Het zeil komt pal voor de wind over; na de gijp zit de stuurman aan de hoge zijde en vaart het schip een vloeiende koers. Zeilstand klopt direct voor en na de manoeuvre — vooral het vieren van de schoot moet snel.$$),
('kielboot-1', 'kielboot-1.p9',  'praktijk',  9, $$Afvaren van hogerwal$$,
 $$Kop nagenoeg in de wind, landvasten los, opgeschoten en paraat opgeborgen. Bemanning evenredig over stuurboord en bakboord, stuurman aan de toekomstige loefzijde, schoten goed los. Goed uitkijken, dan afzetten onder een zo groot mogelijke hoek met de wal, of recht achteruit. Zo nodig fok bak; de afduwer gaat aan loef naar de kuip.$$),
('kielboot-1', 'kielboot-1.p10', 'praktijk', 10, $$Onder toezicht aankomen aan hogerwal$$,
 $$In principe aan de wind aankomen; een stukje tegen de wind in opschieten mag. De snelheid wordt met de zeilen geregeld. De instructeur mag aanwijzingen geven om het veilig te laten verlopen.$$),
('kielboot-1', 'kielboot-1.p11', 'praktijk', 11, $$Afmeren op de eigen ligplaats$$,
 $$Het schip op de eigen ligplaats afmeren, stootkussens gebruiken waar beschadiging dreigt, en de juiste knopen en steken gebruiken.$$),
('kielboot-1', 'kielboot-1.p12', 'praktijk', 12, $$De noodzaak van het reven onderkennen$$,
 $$Kunnen aangeven wanneer er gereefd moet worden, op grond van schip, zeilwater, windkracht en de geoefendheid van de bemanning. Het reven zelf hoeft op dit niveau nog niet.$$),
('kielboot-1', 'kielboot-1.p13', 'praktijk', 13, $$Toepassing van de reglementen$$,
 $$De uitwijkregels voor het eigen vaargebied toepassen en een uitwijkmanoeuvre tijdig inzetten. De bemanning mag waarschuwen voor andere scheepvaart.$$),

-- ---------------- Kielboot I — theorie
('kielboot-1', 'kielboot-1.t1', 'theorie', 1, $$Schiemanswerk$$,
 $$Kennen en kunnen leggen: achtknoop, twee halve steken (de eerste slippend), paalsteek, reefsteek (platte knoop), en het beleggen op klamp, nagel of kikker. Ook een tros kunnen opschieten.$$),
('kielboot-1', 'kielboot-1.t2', 'theorie', 2, $$Zeiltermen$$,
 $$Weten wat bedoeld wordt met: hogerwal, lagerwal, bakboord, stuurboord, hoge en lage zijde, loef- en lijzijde, in de wind, aan de wind, halve wind, ruime wind, voor de wind, oploeven, afvallen, overstag gaan, gijpen, kruisrak, killen van het zeil.$$),
('kielboot-1', 'kielboot-1.t3', 'theorie', 3, $$Onderdelen$$,
 $$Van eigen boot en tuigage, in de praktijk en op een tekening, minstens 15 onderdelen bij de juiste naam noemen (naar keuze van de kandidaat).$$),
('kielboot-1', 'kielboot-1.t4', 'theorie', 4, $$Veiligheid$$,
 $$Kunnen uitleggen waarom je bij een omgeslagen boot blijft, en de eisen kennen die aan een reddingvest gesteld worden.$$),
('kielboot-1', 'kielboot-1.t5', 'theorie', 5, $$Reglementen$$,
 $$Uit het Binnenvaartpolitiereglement kunnen toepassen: groot en klein schip (1.01), voorzorgsmaatregelen (1.04), afwijking van het reglement (1.05), tegengestelde koersen met stuurboordwal en voorrang van groot op klein (6.04), en kruisende koersen inclusief kleine zeilschepen onderling en de volgorde zeil - spier - motor (6.17).$$),
('kielboot-1', 'kielboot-1.t6', 'theorie', 6, $$Krachten op het schip en hun gevolgen$$,
 $$Kunnen aangeven wat fok en grootzeil doen met het sturen van het schip, en wat er gebeurt bij een onjuiste zeilstand.$$),

-- ---------------- Kielboot II — praktijk
('kielboot-2', 'kielboot-2.p1',  'praktijk',  1, $$Het schip zeilklaar en nachtklaar maken$$,
 $$Als bij Kielboot I, maar uitgebreider: zeilkleden met de droge zijde droog opvouwen, sluitingen controleren, kraanlijn aanslaan en doorzetten, fok aanslaan met de leuvers van onderaf en het zeil niet in het water, fokkenschoten door de lij-ogen met een achtknoop erop. Zo nodig reven, zelflozers instellen. De bemanning is goed gekleed en kan zich omkleden als het weer omslaat; voor iedereen een reddingvest aan boord.$$),
('kielboot-2', 'kielboot-2.p2',  'praktijk',  2, $$Verhalen van het schip$$,
 $$Zonder motor. Alle manieren op spierkracht mogen, zolang het geen gevaar oplevert voor bemanning, materiaal of andere scheepvaart. Op het schip zelf zo veel mogelijk vanuit de kuip werken.$$),
('kielboot-2', 'kielboot-2.p3',  'praktijk',  3, $$Stilliggend hijsen en strijken van de zeilen$$,
 $$Kop nagenoeg in de wind, bemanning voorin of aan de kant van de kraanlijn. Grootzeil: schoot en zeilbandjes los, bij gaffelzeil gaffel op circa 45 graden, vallen samen, klauwval vast, halstalie vast, piek stellen tot er een plooi van nok naar hals staat. Fok: schoothoek lostrekken, hijsen, strietsen, val beleggen, vallen en kraanlijn opschieten.$$),
('kielboot-2', 'kielboot-2.p4',  'praktijk',  4, $$Stand en bediening van de zeilen$$,
 $$Op rechte koers en in de bocht zo veel mogelijk de juiste zeilstand: zo ver gevierd als kan zonder dat het voorlijk kilt, met bescheiden killen van de fok bij oploeven en van het grootzeil bij afvallen. De zeilen ondersteunen het sturen.$$),
('kielboot-2', 'kielboot-2.p5',  'praktijk',  5, $$Sturen, roer- en schootbediening$$,
 $$Met roer en zeilen een rechte koers en bochten varen, zó dat een aangewezen punt zonder onnodige omwegen wordt aangezeild.$$),
('kielboot-2', 'kielboot-2.p6',  'praktijk',  6, $$Overstag gaan$$,
 $$Van hoog aan de wind over de ene boeg naar hoog aan de wind over de andere, met de commando's klaar om te wenden, ree, zo nodig fok bak, fok over en fok aan. De fok wordt zonder rukken strak gezet, er wordt zo min mogelijk roer gegeven, en de stuurman gaat met het gezicht naar voren verzitten.$$),
('kielboot-2', 'kielboot-2.p7',  'praktijk',  7, $$Opkruisen in nauw vaarwater$$,
 $$Goed hoog aan de wind zeilen met de rest van het scheepvaartverkeer in de gaten. Waait de wind van een van de oevers, dan vaar je de korte slag met een knik in de schoot, om genoeg snelheid te houden voor een vloeiende overstagmanoeuvre.$$),
('kielboot-2', 'kielboot-2.p8',  'praktijk',  8, $$Gijpen en gijpen kunnen vermijden$$,
 $$Gijpen als bij Kielboot I, maar nu ook kunnen vermijden als de omstandigheden dat vragen: een stormrondje varen — rustig oploeven, na de overstagmanoeuvre vlot afvallen met het grootzeil flink los en de fok bak — of het grootzeil strijken.$$),
('kielboot-2', 'kielboot-2.p9',  'praktijk',  9, $$Afvaren van hogerwal$$,
 $$Als bij Kielboot I, en zo nodig deinzend: schip in de wind, gewicht evenredig verdeeld, schoten los, fok gebundeld, stuurman aan de toekomstige loefzijde. De afduwer houdt het schip aan de voorstag vast en zet krachtig recht achteruit af; de roerganger geeft roer voor een deinzend schip en valt vol over de vooraf afgesproken boeg, bij voorkeur zonder fok bak.$$),
('kielboot-2', 'kielboot-2.p10', 'praktijk', 10, $$Aankomen aan hogerwal (onder alle omstandigheden)$$,
 $$Ook zonder dwarspeiling. Landvasten klaar en aan het schip vast. Het schip ligt stil vlak voor de aangewezen plaats, op een aan de windse koers en zo veel mogelijk loodrecht op de wal; de snelheidsregeling is zichtbaar en de zeilen killen volledig. Wie vastmaakt blijft zo lang mogelijk laag, met het landvast in de hand, en stapt via de loefzijde aan wal — niet springen.$$),
('kielboot-2', 'kielboot-2.p11', 'praktijk', 11, $$Afmeren van het schip$$,
 $$Zo vastleggen dat ook op lange termijn geen schade aan eigen of andere schepen mogelijk is. Minder dan 3 of meer dan 6 lijnen naar de wal is altijd fout; kies ze zo lang mogelijk en leg eerst de lijnen vast die de natuurlijke beweging van het schip tegengaan.$$),
('kielboot-2', 'kielboot-2.p12', 'praktijk', 12, $$Kunnen reven op het eigen schip$$,
 $$Kunnen aangeven wanneer reven nodig is — op grond van schip, zeilwater, windkracht en geoefendheid van de bemanning — en het op de eigen boot ook daadwerkelijk kunnen.$$),
('kielboot-2', 'kielboot-2.p13', 'praktijk', 13, $$Toepassing van de reglementen$$,
 $$De uitwijkregels voor het eigen vaargebied toepassen en een uitwijkmanoeuvre tijdig inzetten. De bemanning mag waarschuwen voor andere scheepvaart.$$),
('kielboot-2', 'kielboot-2.p14', 'praktijk', 14, $$Man over boord manoeuvre$$,
 $$Constateren en roepen, "zwem" toeroepen, drijfmiddel toewerpen, iemand laten wijzen. Vanaf elke koers afvallen naar voor de wind, doorvaren tot je over de aan de windse lijn heen bent (zo'n 4 bootlengtes), oploeven, "man dwars", overstag, snelheid regelen en langzaam aan lij langsvaren. Bemanning klaar aan loef, "man vast", fok bak. De drenkeling aan loef op het draaipunt achter het want zijdelings en horizontaal binnenhalen. Bijliggen en EHBO toepassen.$$),
('kielboot-2', 'kielboot-2.p15', 'praktijk', 15, $$Loskomen van aan de grond$$,
 $$In volgorde van moeilijkheid: zo snel mogelijk van de ondiepte af sturen; het schip krengen om diepgang te verminderen (pas op voor de gijp bij voor de windse koersen); de vaarboom pakken en door de wind bomen of een gijp forceren; en als laatste het zeil strijken en de boot dezelfde weg terugduwen of laten slepen.$$),
('kielboot-2', 'kielboot-2.p16', 'praktijk', 16, $$Gebruik buitenboordmotor$$,
 $$Met minstens één motor overweg kunnen: start- en stopprocedure kennen, zo nodig de choke, en controleren of het roer de schroef kan raken. Aanleggen en afvaren van hogerwal, goed afmeren op de eigen ligplaats, keren en stoppen. Zijn er mensen in het water vlakbij, dan gaat de motor uit.$$),

-- ---------------- Kielboot II — theorie
('kielboot-2', 'kielboot-2.t1', 'theorie', 1, $$Schiemanswerk$$,
 $$Bij naam kennen, kunnen leggen en de functie kennen van: twee halve steken (de eerste slippend), achtknoop, paalsteek, platte knoop, mastworp (met slipsteek als borg), enkele schootsteek. Plus een lijn opschieten en beleggen op een kikker.$$),
('kielboot-2', 'kielboot-2.t2', 'theorie', 2, $$Zeiltermen$$,
 $$De termen van Kielboot I, aangevuld met deinzen, opschieten en beleggen.$$),
('kielboot-2', 'kielboot-2.t3', 'theorie', 3, $$Onderdelen$$,
 $$Van eigen boot en tuigage, in de praktijk en op een tekening, minstens 25 onderdelen bij naam noemen. In ieder geval: blok, landvast, kiel, helmstok, roer, mast, giek, val, schoot, halshoek, schoothoek, grootzeil, fok.$$),
('kielboot-2', 'kielboot-2.t4', 'theorie', 4, $$Veiligheid$$,
 $$Kunnen uitleggen waarom je bij een omgeslagen boot blijft, en de eisen kennen die aan een reddingvest gesteld worden.$$),
('kielboot-2', 'kielboot-2.t5', 'theorie', 5, $$Reglementen$$,
 $$Uit het BPR: de begripsbepalingen voor motorschip, groot en klein schip, zeilschip en zeilplank (1.01), voorzorgsmaatregelen (1.04), afwijking (1.05), tegengestelde koersen inclusief kleine zeilschepen onderling en zeil - spier - motor (6.01, 6.03, 6.04), voorbijlopen (6.10) en kruisende koersen (6.17). Ook weten dat er naast het BPR andere reglementen gelden en waar je die vindt.$$),
('kielboot-2', 'kielboot-2.t6', 'theorie', 6, $$Krachten op het schip en hun gevolgen$$,
 $$Wat fok en grootzeil doen met het sturen, wat er gebeurt bij een onjuiste zeilstand, en wat de helling van de boot met de sturing doet.$$),
('kielboot-2', 'kielboot-2.t7', 'theorie', 7, $$Gedragsregels$$,
 $$De goede gebruiken ten opzichte van andere watersporters kennen, waaronder wedstrijdzeilers, en de verantwoording ten opzichte van het milieu.$$),
('kielboot-2', 'kielboot-2.t8', 'theorie', 8, $$Weersinvloeden$$,
 $$Het weerbericht kunnen interpreteren met het oog op de veiligheid van het kielbootvaren en de eigen vaardigheid, en voortekenen van plotselinge weersomslagen zoals onweer en zware windvlagen tijdig herkennen.$$),
('kielboot-2', 'kielboot-2.t9', 'theorie', 9, $$Vaarproblematiek andersoortige schepen$$,
 $$Het gevaar kennen van de dode hoek en van de zuiging van grote schepen. Weten dat grote schepen op smal vaarwater niet kunnen wijken, en dat ook grote vrachtschepen sterk kunnen verlijeren.$$),

-- ---------------- Kielboot III — praktijk
('kielboot-3', 'kielboot-3.p1',  'praktijk',  1, $$Het aanslaan van de zeilen$$,
 $$Een zeil kunnen aanslaan aan de rondhouten van het eigen schip.$$),
('kielboot-3', 'kielboot-3.p2',  'praktijk',  2, $$Het schip zeilklaar maken en klaarmaken voor de nacht$$,
 $$Als bij Kielboot II: inventaris, zeilkleden droog opvouwen, kraanlijn aanslaan en doorzetten, mik of schaar veilig opbergen, fok aanslaan met de leuvers van onderaf, fokkenschoten door de lij-ogen met achtknoop, grootzeilvallen aanslaan, zo nodig reven, zelflozers instellen. Bemanning goed gekleed met de mogelijkheid zich om te kleden, en voor iedereen een reddingvest.$$),
('kielboot-3', 'kielboot-3.p3',  'praktijk',  3, $$Verhalen van het schip$$,
 $$Zonder motor, op spierkracht, zonder gevaar voor bemanning, materiaal of andere scheepvaart, en op het schip zelf zo veel mogelijk vanuit de kuip.$$),
('kielboot-3', 'kielboot-3.p4',  'praktijk',  4, $$Hijsen en strijken van de zeilen, stilliggend en varend$$,
 $$Stilliggend als bij Kielboot II. Varend: fokkenval vast aan de nagelbank, nog één zeilbandje met slipsteek, kraanlijn strak aan de toekomstige loefzijde, schoot met slipsteek klaar. Op koersen hoger dan halve wind eerst het grootzeil en dan de fok; op ruimere koersen eerst de fok, vaart maken, oploeven tot aan de wind en dan het grootzeil. Let goed op het andere scheepvaartverkeer.$$),
('kielboot-3', 'kielboot-3.p5',  'praktijk',  5, $$Stand en bediening van de zeilen$$,
 $$Op rechte koers en in de bocht zo veel mogelijk de juiste zeilstand: zo ver gevierd als kan zonder dat het voorlijk kilt. De zeilen ondersteunen het sturen.$$),
('kielboot-3', 'kielboot-3.p6',  'praktijk',  6, $$Bovenwinds gelegen punt kunnen bezeilen$$,
 $$Met zo min mogelijk slagen een in de wind gelegen punt bezeilen, en met de "achterlijker dan dwars"-peiling goed bepalen wanneer je overstag kunt. Moeten er een lange en een korte slag gemaakt worden, dan bij voorkeur met de korte slag bij het punt aankomen.$$),
('kielboot-3', 'kielboot-3.p7',  'praktijk',  7, $$Opkruisen in nauw vaarwater$$,
 $$Goed hoog aan de wind zeilen met oog voor het andere verkeer. Waait de wind van een van de oevers, dan de korte slag met een knik in de schoot varen voor genoeg snelheid om vloeiend overstag te kunnen.$$),
('kielboot-3', 'kielboot-3.p8',  'praktijk',  8, $$Gijpen en gijpen kunnen vermijden$$,
 $$De gijp zien aankomen en de bemanning waarschuwen; het zeil komt pal voor de wind over en het schip blijft een vloeiende koers varen. Vermijden kan met een stormrondje — rustig oploeven, na de overstagmanoeuvre vlot afvallen met het grootzeil los en de fok bak — of door het grootzeil te strijken.$$),
('kielboot-3', 'kielboot-3.p9',  'praktijk',  9, $$Afvaren van en aankomen aan hogerwal$$,
 $$Afvaren als bij Kielboot II, zo nodig deinzend. Aankomen moet ook zonder dwarspeiling: landvasten klaar en vast aan het schip, stilliggen vlak voor de aangewezen plaats op een aan de windse koers, zo veel mogelijk loodrecht op de wal, met zichtbare snelheidsregeling en volledig killende zeilen. Wie vastmaakt blijft laag en stapt via loef aan wal — niet springen.$$),
('kielboot-3', 'kielboot-3.p10', 'praktijk', 10, $$Man over boord manoeuvre$$,
 $$Constateren en roepen, "zwem" toeroepen, drijfmiddel toewerpen, laten wijzen. Afvallen naar voor de wind tot je over de aan de windse lijn heen bent (zo'n 4 bootlengtes), oploeven, "man dwars", overstag, snelheid regelen en langzaam aan lij langsvaren. "Man vast", fok bak, de drenkeling aan loef op het draaipunt achter het want zijdelings en horizontaal binnenhalen. Bijliggen en EHBO toepassen.$$),
('kielboot-3', 'kielboot-3.p11', 'praktijk', 11, $$Aankomen aan lagerwal$$,
 $$Stootwillen op de juiste plaats, afstoplijn klaar bij het draaipunt, vallen vrij uitlopend, kraanlijn aan de toekomstige loefzijde. Fok zo nodig eerst strijken, grootzeil bovenwinds strijken op aan de windse koers: voorstrijk, grootschoot vast, vlot strijken, aan loef binnenhalen, zeilbandjes vast. Aankomen via de opdraaimethode of met de afstoplijn. Houd het schip vierkant, bemanning laag in de kuip en mee uitkijken, en houd nooit met handen of voeten af.$$),
('kielboot-3', 'kielboot-3.p12', 'praktijk', 12, $$Afmeren$$,
 $$Zo vastleggen dat ook op lange termijn geen schade mogelijk is. Minder dan 3 of meer dan 6 lijnen naar de wal is altijd fout; zo lang mogelijk gekozen, en eerst de lijnen die de natuurlijke beweging van het schip tegengaan.$$),
('kielboot-3', 'kielboot-3.p13', 'praktijk', 13, $$Kunnen reven op het eigen schip$$,
 $$Kunnen aangeven wanneer reven nodig is — schip, zeilwater, windkracht, geoefendheid van de bemanning — en het op de eigen boot ook kunnen.$$),
('kielboot-3', 'kielboot-3.p14', 'praktijk', 14, $$Eenvoudig ankeren$$,
 $$In een noodgeval het aanwezige anker kunnen gebruiken: geen lijnen om het anker, het anker moet zich kunnen ingraven, en het schip blijft tijdens het ankeren nagenoeg in de wind liggen.$$),
('kielboot-3', 'kielboot-3.p15', 'praktijk', 15, $$Eenvoudige zeil- en scheepstrim$$,
 $$De functie van de bolling van het zeil kennen en die zo nodig kunnen beïnvloeden. De helling van het schip blijft zo veel mogelijk constant, een ietsje naar lij.$$),
('kielboot-3', 'kielboot-3.p16', 'praktijk', 16, $$Loskomen van aan de grond$$,
 $$In volgorde van moeilijkheid: van de ondiepte af sturen; krengen om diepgang te verminderen (let op de gijp bij voor de windse koersen); de vaarboom pakken en door de wind bomen of een gijp forceren; en als laatste het zeil strijken en dezelfde weg terugduwen of laten slepen.$$),
('kielboot-3', 'kielboot-3.p17', 'praktijk', 17, $$Bedienen van een binnen- of buitenboordmotor$$,
 $$Met minstens één motor overweg kunnen: start- en stopprocedure, zo nodig de choke, en bij een buitenboordmotor controleren of het roer de schroef kan raken. Aanleggen en afvaren van hogerwal, afmeren op de eigen ligplaats, keren, stoppen en stilliggen op open water. Zijn er mensen in het water vlakbij, dan gaat de motor uit.$$),
('kielboot-3', 'kielboot-3.p18', 'praktijk', 18, $$Schiemanswerk$$,
 $$Weten welk touwwerk waarvoor geschikt is — landvasten, vallen, sleeplijn, ankerlijn — en het vrij van zand, scherpe randen en UV-licht houden. Steken en knopen met hun toepassing: twee halve steken, slipsteek, achtknoop, platte knoop, enkele en dubbele schootsteek, mastworp op twee manieren, paalsteek, een tros opschieten, beleggen op bolder, klamp of nagel.$$),
('kielboot-3', 'kielboot-3.p19', 'praktijk', 19, $$Aanvarings- en achtergrondpeiling kunnen maken$$,
 $$Bij kruisende koersen vaststellen of er aanvaringsgevaar ontstaat, door over het andere schip een peiling op de achtergrond te nemen.$$),
('kielboot-3', 'kielboot-3.p20', 'praktijk', 20, $$Toepassing van de reglementen$$,
 $$De uitwijkregels voor het eigen vaargebied toepassen en een uitwijkmanoeuvre tijdig inzetten. De bemanning mag waarschuwen voor andere scheepvaart.$$),
('kielboot-3', 'kielboot-3.p21', 'praktijk', 21, $$Terminologie$$,
 $$Zo veel mogelijk de juiste naamgeving gebruiken, binnen de boot én tussen schepen en personen onderling.$$),

-- ---------------- Kielboot III — theorie
('kielboot-3', 'kielboot-3.t1',  'theorie',  1, $$Schiemanswerk$$,
 $$De steken van Kielboot II, aangevuld met mastworp en schootsteek op twee manieren, en beleggen op een bolder. Daarnaast: touwsoorten verschillen in rekvermogen, breeksterkte, slijtvastheid, wateropname en UV-bestendigheid; geslagen en gevlochten touwwerk herkennen; weten welk touw waarvoor geschikt is; en het begrip schavielen met de maatregelen daartegen kunnen beschrijven.$$),
('kielboot-3', 'kielboot-3.t2',  'theorie',  2, $$Zeiltermen$$,
 $$De termen van Kielboot II, aangevuld met bovenlangs, onderlangs, dwarspeiling, bezeild, binnen de wind, korte en lange slag, opschieter, zuigen, duiken, planeren, volvallen, verhalen, verlijeren, drift, bijliggen en bakhouden.$$),
('kielboot-3', 'kielboot-3.t3',  'theorie',  3, $$Onderdelen$$,
 $$Van eigen boot en tuigage, in de praktijk en op afbeeldingen, minstens 40 onderdelen bij naam noemen. In ieder geval: voorsteven, spiegel, sluiting, kous, blok, stootkussen, hoosvat, landvast, kiel, helmstok, roer, roerblad, mast, giek, val, halstalie, schoot, voor-, achter- en onderlijk, hals- en schoothoek, grootzeil, fok.$$),
('kielboot-3', 'kielboot-3.t4',  'theorie',  4, $$Veiligheid$$,
 $$Kunnen uitleggen waarom je bij een omgeslagen boot blijft, en de eisen kennen die aan een zwemvest of reddingvest gesteld worden.$$),
('kielboot-3', 'kielboot-3.t5',  'theorie',  5, $$Reglementen$$,
 $$Een flink uitgebreidere lijst uit het BPR dan bij Kielboot II: begripsbepalingen, tekens en lichten, geluidsseinen en verkeerstekens, de vaarregels, bruggen en sluizen. Ook weten welke andere reglementen in het eigen vaargebied gelden, waar je ze vindt, en dat voor bepaalde schepen een Klein Vaarbewijs verplicht is. De volledige artikelopsomming staat in het handboek.$$),
('kielboot-3', 'kielboot-3.t6',  'theorie',  6, $$Krachten op het schip en hun gevolgen$$,
 $$De begrippen kracht en koppel kennen en kunnen gebruiken: wat fok en grootzeil met het sturen doen, wat een onjuiste zeilstand oplevert, wat de helling doet, en hoe uit de windkracht op het zeil zowel drift als voortstuwing ontstaat. Plus de oorzaken van stabiliteit bij scherpe jachten, en het verschil tussen gewichts- en vormstabiliteit.$$),
('kielboot-3', 'kielboot-3.t7',  'theorie',  7, $$Gedragsregels, vlagvoering en jachtetiquette$$,
 $$De goede gebruiken ten opzichte van andere watersporters kennen, waaronder wedstrijdzeilers, de verantwoording ten opzichte van het milieu, en de vlagvoering van het eigen schip.$$),
('kielboot-3', 'kielboot-3.t8',  'theorie',  8, $$Weersinvloeden$$,
 $$Het weerbericht kunnen interpreteren met het oog op veiligheid en eigen vaardigheid, en voortekenen van plotselinge weersomslagen tijdig herkennen. Ook weten welke windsnelheden in m/s bij de stappen van de schaal van Beaufort horen, en hoe de omschrijvingen in waarschuwingen daarmee samenhangen.$$),
('kielboot-3', 'kielboot-3.t9',  'theorie',  9, $$Vaarproblematiek andersoortige schepen$$,
 $$Het gevaar kennen van de dode hoek en van de zuiging van grote schepen. Weten dat grote schepen op smal vaarwater niet kunnen wijken, en dat ook grote vrachtschepen sterk kunnen verlijeren.$$),
('kielboot-3', 'kielboot-3.t10', 'theorie', 10, $$Dagelijks onderhoud van het eigen schip$$,
 $$Controleren of bevestigingsmaterialen vastzitten, ook boven in de mast; kleine beschadigingen bijwerken; het schip schoonhouden. Voor de buitenboordmotor: brandstof bijvullen, smering van motor en schroefas controleren, en vreemde geluiden herkennen en doorgeven.$$),
('kielboot-3', 'kielboot-3.t11', 'theorie', 11, $$Het kennen van twee andere reefsystemen dan die op het eigen schip$$,
 $$Theoretische kennis van het reefsysteem van het eigen schip en van de belangrijkste foutoorzaken daarbij, plus twee andere reefsystemen kennen.$$),

-- ---------------- Kielboot IV — praktijk
('kielboot-4', 'kielboot-4.p1',  'praktijk',  1, $$Aanslaan van de zeilen$$,
 $$Een zeil kunnen aanslaan aan de rondhouten van het eigen schip.$$),
('kielboot-4', 'kielboot-4.p2',  'praktijk',  2, $$Schip zeilklaar maken en klaarmaken voor de nacht$$,
 $$Als bij Kielboot III: inventaris, zeilkleden droog opvouwen en niet in de weg opbergen, kraanlijn aanslaan en doorzetten, fok aanslaan met de leuvers van onderaf, fokkenschoten door de lij-ogen met achtknoop, grootzeilvallen aanslaan, zo nodig reven, zelflozers instellen. Bemanning goed gekleed en in staat zich om te kleden, en voor iedereen een reddingvest.$$),
('kielboot-4', 'kielboot-4.p3',  'praktijk',  3, $$Verhalen van het schip$$,
 $$Zonder motor, op spierkracht, zonder gevaar voor bemanning, materiaal of andere scheepvaart, en op het schip zelf zo veel mogelijk vanuit de kuip.$$),
('kielboot-4', 'kielboot-4.p4',  'praktijk',  4, $$Hijsen en strijken van de zeilen, stilliggend en varend$$,
 $$Als bij Kielboot III. Varend: fokkenval vast aan de nagelbank, één zeilbandje met slipsteek, kraanlijn strak aan de toekomstige loefzijde, grootschoot met slipsteek klaar. Op koersen hoger dan halve wind eerst grootzeil dan fok; op ruimere koersen eerst de fok, vaart maken, oploeven en dan het grootzeil. Bij weinig wind, vaak bij bruggen, mag het grootzeil ook op ruimere koers omhoog.$$),
('kielboot-4', 'kielboot-4.p5',  'praktijk',  5, $$Stand en bediening van de zeilen$$,
 $$Op rechte koers en in de bocht zo veel mogelijk de juiste zeilstand: zo ver gevierd als kan zonder dat het voorlijk kilt. De zeilen ondersteunen het sturen.$$),
('kielboot-4', 'kielboot-4.p6',  'praktijk',  6, $$Bovenwinds gelegen punt kunnen bezeilen$$,
 $$Met zo min mogelijk slagen, en met de "achterlijker dan dwars"-peiling bepalen wanneer je overstag kunt. Bij een lange en een korte slag bij voorkeur met de korte slag bij het punt aankomen.$$),
('kielboot-4', 'kielboot-4.p7',  'praktijk',  7, $$Opkruisen in nauw vaarwater$$,
 $$Goed hoog aan de wind zeilen met oog voor het andere verkeer, en bij wind van een van de oevers de korte slag met een knik in de schoot varen.$$),
('kielboot-4', 'kielboot-4.p8',  'praktijk',  8, $$Gijpen en gijpen kunnen vermijden$$,
 $$De gijp zien aankomen en de bemanning waarschuwen; het zeil komt pal voor de wind over en het schip blijft een vloeiende koers varen. Vermijden kan met een stormrondje of door het grootzeil te strijken.$$),
('kielboot-4', 'kielboot-4.p9',  'praktijk',  9, $$Afvaren van en aankomen aan hogerwal$$,
 $$Als bij Kielboot III, zo nodig deinzend, en aankomen ook zonder dwarspeiling: stilliggen vlak voor de aangewezen plaats op een aan de windse koers, loodrecht op de wal, met zichtbare snelheidsregeling en volledig killende zeilen. Via loef aan wal stappen, niet springen.$$),
('kielboot-4', 'kielboot-4.p10', 'praktijk', 10, $$Man over boord manoeuvre kunnen uitvoeren$$,
 $$Constateren, "zwem" toeroepen, drijfmiddel toewerpen, laten wijzen. Afvallen naar voor de wind tot over de aan de windse lijn (zo'n 4 bootlengtes), oploeven, "man dwars", overstag, snelheid regelen en langzaam aan lij komen. "Man vast", fok bak, de drenkeling aan loef op het draaipunt achter het want zijdelings en horizontaal binnenhalen. Bijliggen en EHBO toepassen.$$),
('kielboot-4', 'kielboot-4.p11', 'praktijk', 11, $$Wegvaren van en aankomen aan lagerwal$$,
 $$Afvaren: vaarboom klaar aan de walzijde, schip zo nodig eerst draaien, en bepalen of het door de wind gedrukt moet worden (weinig wind) of juist niet (zwaar schip of veel wind). Vaart geven via vaarboom, giek of want, en de periode zonder zeil zo kort mogelijk houden. Aankomen als bij Kielboot III: stootwillen, afstoplijn bij het draaipunt, grootzeil bovenwinds strijken, dan de opdraai- of afstopmethode.$$),
('kielboot-4', 'kielboot-4.p12', 'praktijk', 12, $$Afmeren$$,
 $$Zo vastleggen dat ook op lange termijn geen schade mogelijk is. Minder dan 3 of meer dan 6 lijnen naar de wal is altijd fout; zo lang mogelijk gekozen, en eerst de lijnen die de natuurlijke beweging van het schip tegengaan.$$),
('kielboot-4', 'kielboot-4.p13', 'praktijk', 13, $$Kunnen reven op het eigen schip$$,
 $$Kunnen aangeven wanneer reven nodig is — schip, zeilwater, windkracht, geoefendheid van de bemanning — en het op de eigen boot ook kunnen.$$),
('kielboot-4', 'kielboot-4.p14', 'praktijk', 14, $$Ankeren en anker op gaan$$,
 $$Ankeren: proefopschieter op de ankerplaats, grondgesteldheid en diepte bepalen, ankertros vast aan een degelijk punt, ankerboei vast. Met gestreken fok stilliggen, anker laten vallen zodra het schip stilligt (niet werpen), tros vieren, zeil strijken zodra het anker houdt, ankerbol hijsen. Regelmatig controleren op krabben. Anker op: tros aan de toekomstige loefzijde, ankerbol strijken, tros inhalen, grootzeil hijsen, anker ophalen en over de gekozen boeg wegvaren, anker schoonmaken.$$),
('kielboot-4', 'kielboot-4.p15', 'praktijk', 15, $$Varen in kanalen, passeren van bruggen en sluizen$$,
 $$De bijbehorende technieken en gedragsregels kennen: op je beurt wachten, geen rondjes varen voor de brugopening, zo nodig een sleepje vragen of accepteren, de ketting gebruiken om door de brug te komen, en zo nodig de mast strijken voor een rustige passage.$$),
('kielboot-4', 'kielboot-4.p16', 'praktijk', 16, $$Doelmatigheid in vaargedrag vertonen$$,
 $$Met grote nauwkeurigheid varen: zo min mogelijk gevaren meters tussen de opdracht en de uitvoering, en reglementproblemen inzichtelijk voorkomen.$$),
('kielboot-4', 'kielboot-4.p17', 'praktijk', 17, $$Zeil- en scheepstrim$$,
 $$De bolling van het zeil kunnen beïnvloeden en de functie kennen van de spanning op de lijkenbindsels, de helling van de gaffel en de halstalie; voor de fok de reguleerlijntjes in voor- en achterlijk en de verstelbare lij-ogen. De helling blijft constant, een ietsje naar lij, en de langsscheepse ballastverdeling geeft zo min mogelijk turbulentie.$$),
('kielboot-4', 'kielboot-4.p18', 'praktijk', 18, $$Loskomen van aan de grond$$,
 $$In volgorde van moeilijkheid: van de ondiepte af sturen; krengen om diepgang te verminderen; de vaarboom pakken en door de wind bomen of een gijp forceren; en als laatste het zeil strijken en dezelfde weg terugduwen of laten slepen.$$),
('kielboot-4', 'kielboot-4.p19', 'praktijk', 19, $$Bedienen van een binnen- of buitenboordmotor$$,
 $$Start- en stopprocedure, zo nodig de choke, en bij een buitenboordmotor controleren of het roer de schroef kan raken. Aanleggen en afvaren van hoger- én lagerwal, afmeren op de eigen ligplaats, keren, stoppen en stilliggen op open water. Zijn er mensen in het water vlakbij, dan gaat de motor uit.$$),
('kielboot-4', 'kielboot-4.p20', 'praktijk', 20, $$Schiemanswerk$$,
 $$Als bij Kielboot III — touwsoorten en hun gebruik, twee halve steken, slipsteek, achtknoop, platte knoop, enkele en dubbele schootsteek, mastworp op twee manieren, paalsteek, opschieten en beleggen — aangevuld met een splits in driestrengs touwwerk en een benaaide takeling.$$),
('kielboot-4', 'kielboot-4.p21', 'praktijk', 21, $$Aanvarings- en achtergrondpeiling kunnen maken$$,
 $$Bij kruisende koersen vaststellen of er aanvaringsgevaar ontstaat, door over het andere schip een peiling op de achtergrond te nemen.$$),
('kielboot-4', 'kielboot-4.p22', 'praktijk', 22, $$Toepassing van de reglementen$$,
 $$De uitwijkregels kunnen toepassen, en een uitwijkmanoeuvre tijdig inzetten.$$),
('kielboot-4', 'kielboot-4.p23', 'praktijk', 23, $$Terminologie$$,
 $$Zo veel mogelijk de juiste naamgeving gebruiken, binnen de boot én tussen schepen en personen onderling.$$),

-- ---------------- Kielboot IV — theorie
('kielboot-4', 'kielboot-4.t1',  'theorie',  1, $$Schiemanswerk$$,
 $$Het verschil tussen gevlochten en geslagen touwwerk kunnen aangeven — in fabricage, verwerking én gebruik.$$),
('kielboot-4', 'kielboot-4.t2',  'theorie',  2, $$Dagelijks onderhoud van het eigen schip en de binnen- of buitenboordmotor$$,
 $$Controle op het vastzitten van bevestigingsmaterialen, ook boven in de mast; kleine beschadigingen bijwerken; het schip schoonhouden. Motor: brandstof bijvullen, smering van motor en schroefas controleren en aanvullen, vreemde geluiden herkennen en doorgeven. Lensruimte schoonhouden en vervuild lenswater inleveren bij een depot.$$),
('kielboot-4', 'kielboot-4.t3',  'theorie',  3, $$Scheepsbouw, materialen en onderdelen$$,
 $$Benaming, toepassing en functie van scheepsonderdelen, met de voor- en nadelen van verschillende systemen. Jachten onderscheiden naar hoofdtype (scherpe jachten, ronde en platbodems, meerrompsjachten) en hoofdspantvorm (rondspant, knikspant, S-spant). Verder: romponderdelen, driftbeperking (kiel, midzwaard, zijzwaarden), roerconstructies (aangehangen en doorgestoken), rondhouten, staand en lopend want, de zeilen en hun onderdelen, en de reefsystemen.$$),
('kielboot-4', 'kielboot-4.t4',  'theorie',  4, $$Veiligheid en (blessure)preventie$$,
 $$De veiligheid van de opvarenden moet preventief gewaarborgd zijn — in het schip zelf, in de kleding en in de veiligheidsmiddelen.$$),
('kielboot-4', 'kielboot-4.t5',  'theorie',  5, $$Reglementen$$,
 $$De uitgebreide BPR-lijst van Kielboot III, maar nu nadrukkelijk in toepassing: artikelen uit het hoofd kennen is niet genoeg, je moet ze op geschetste situaties kunnen toepassen. Het handboek waarschuwt dat dit onderdeel op het examen het lastigst blijkt. Ook weten welke andere reglementen in het eigen vaargebied gelden en dat voor bepaalde schepen een Klein Vaarbewijs verplicht is.$$),
('kielboot-4', 'kielboot-4.t6',  'theorie',  6, $$Navigatie$$,
 $$De betekenis van de rode en groene tonnen en de splitsingstonnen volgens het SIGNI-systeem kennen, en overweg kunnen met waterkaarten en de Almanak voor Watertoerisme deel 2.$$),
('kielboot-4', 'kielboot-4.t7',  'theorie',  7, $$Vaarproblematiek grote schepen$$,
 $$Besef hebben van de problemen van de grote scheepvaart, met de begrippen diepgang, dode hoek, windvang in ongeladen toestand, zuiging en benodigde manoeuvreerruimte.$$),
('kielboot-4', 'kielboot-4.t8',  'theorie',  8, $$Vlagvoering en jachtetiquette$$,
 $$De vlagvoering voor schepen met één mast kennen, de verantwoording ten aanzien van het milieu, en de goede gebruiken ten opzichte van andere watersporters en wedstrijdzeilers.$$),
('kielboot-4', 'kielboot-4.t9',  'theorie',  9, $$Stabiliteit$$,
 $$De oorzaken van stabiliteit kennen bij scherpe jachten, bij platbodems en ronde schepen, en bij meerrompsjachten.$$),
('kielboot-4', 'kielboot-4.t10', 'theorie', 10, $$Voortstuwende en remmende krachten$$,
 $$Met vectoren kunnen aangeven waarom een schip vooruit gaat, met de begrippen kracht, koppel en moment.$$),
('kielboot-4', 'kielboot-4.t11', 'theorie', 11, $$Ankergerei$$,
 $$De onderdelen schacht, stok, kruis, armen en vloeien kennen; het verschil tussen lichtgewicht- en volgewichtankers kunnen aangeven; en het Hollands stokanker, de dreg, de klapdreg, het Danforth-anker en het ploegschaaranker herkennen en benoemen.$$),
('kielboot-4', 'kielboot-4.t12', 'theorie', 12, $$De meest voorkomende scheepssoorten in het eigen vaargebied herkennen en benoemen$$,
 $$Van minstens de helft van de passerende schepen een naam of een redelijk nauwkeurige type-omschrijving kunnen geven. De examinator kiest zelf de selectie.$$),

-- ---------------- Buitenboordmotor I/II — praktijk
('bbm-12', 'bbm-12.p1',  'praktijk',  1, $$Het schip vaarklaar maken en klaarmaken voor de nacht$$,
 $$Vaarklaar: controleren op lek- en regenwater, en op inventaris, bevestiging van de motor, brandstof en motorolie. De motor moet goed getrimd staan. Nachtklaar: motor loskoppelen van de benzinetank, losse inventaris opruimen, dekzeil erop.$$),
('bbm-12', 'bbm-12.p2',  'praktijk',  2, $$Benzinetank aansluiten$$,
 $$Een losse tank op de juiste manier aansluiten: nippels goed in elkaar, geen lekkage als je in de bal knijpt, en zorgen voor ontluchten en ventileren.$$),
('bbm-12', 'bbm-12.p3',  'praktijk',  3, $$Uitwendige controle van de motor$$,
 $$De motor aan de buitenkant nalopen op beschadiging aan de schroef en op olielekkage.$$),
('bbm-12', 'bbm-12.p4',  'praktijk',  4, $$Starten van de motor$$,
 $$De motor op de juiste manier starten, met goed gebruik van choke en gas.$$),
('bbm-12', 'bbm-12.p5',  'praktijk',  5, $$Controle op goede werking$$,
 $$De motor stationair laten draaien en controleren op overmatig trillen en op het uitlaten van koelwater.$$),
('bbm-12', 'bbm-12.p6',  'praktijk',  6, $$Gestrekte koers varen$$,
 $$Bij geringe zijwind een rechte koers varen over minstens 200 meter.$$),
('bbm-12', 'bbm-12.p7',  'praktijk',  7, $$Stuurwerking van de motor$$,
 $$Met de motor kunnen sturen, en de boot — ook door de motor om te draaien — in de achteruit zetten, laten stoppen of vaart laten minderen.$$),
('bbm-12', 'bbm-12.p8',  'praktijk',  8, $$Vaart minderen en stoppen$$,
 $$Tijdig gas terugnemen; het stoppen gebeurt achteruitslaand, waarbij het schip op koers blijft. Houd rekening met de hekgolf.$$),
('bbm-12', 'bbm-12.p9',  'praktijk',  9, $$Drijvend voorwerp kunnen benaderen$$,
 $$Een drijvende boei benaderen en zo stoppen dat hij zonder veel moeite aan boord genomen kan worden, rekening houdend met stroom en wind. De boei mag varend niet geraakt worden.$$),
('bbm-12', 'bbm-12.p10', 'praktijk', 10, $$Een acht en een slalom kunnen varen$$,
 $$Sturend met de motor een acht varen en een slalom om een aantal boeien.$$),
('bbm-12', 'bbm-12.p11', 'praktijk', 11, $$Afvaren en aankomen aan een langswal$$,
 $$Aankomen op een aangegeven plaats zonder noemenswaardig af te hoeven houden — let erop dat het schip niet meer stuurt zodra de schroef niet in het werk staat. Wegvaren met het juiste gebruik van trossen en springen.$$),
('bbm-12', 'bbm-12.p12', 'praktijk', 12, $$Afmeren$$,
 $$Deugdelijk vastleggen met voor- en achtertros en een voor- of achterspring, met de juiste keuze welke van de twee. Beleggen op bolder of kikker gaat op de juiste manier.$$),
('bbm-12', 'bbm-12.p13', 'praktijk', 13, $$Ankeren en anker op gaan$$,
 $$Ankeren: in de wind varen, de vaart eruit halen, en het anker overboord zetten zodra de boot stilligt, zonder dat het onklaar raakt. Langzaam achteruit varen en voldoende ankerlijn of ketting steken. Anker op: motor stand-by, en het anker op de juiste manier aan boord opbergen.$$),
('bbm-12', 'bbm-12.p14', 'praktijk', 14, $$Brandstof bijvullen$$,
 $$Met de nodige voorzorgen: losse tanks aan de wal vullen, en maatregelen treffen om morsen te voorkomen.$$),
('bbm-12', 'bbm-12.p15', 'praktijk', 15, $$Schiemanswerk$$,
 $$Vlot kunnen leggen: platte knoop, paalsteek, halve steek, mastworp. Plus een lijn opschieten en beleggen op een kikker of bolder.$$),
('bbm-12', 'bbm-12.p16', 'praktijk', 16, $$Terminologie$$,
 $$Afhankelijk van het type schip acht onderdelen kunnen benoemen, met hun functie.$$),

-- ---------------- Buitenboordmotor I/II — theorie
('bbm-12', 'bbm-12.t1', 'theorie', 1, $$Terminologie van schip en motor$$,
 $$Van het schip: boeg, stuurboord, bakboord, steven, spanten, spiegel, motorsteun, vrijboord. Van de motor: bougie, brandstofslang, carburator, koelwateruitlaat, gas- en chokehandel — met hun functie.$$),
('bbm-12', 'bbm-12.t2', 'theorie', 2, $$Meest voorkomende storingen kunnen verhelpen$$,
 $$Een vette bougie herkennen en reinigen, de brandstofslang op verstopping controleren, de mengverhouding van de brandstof kennen, en een breekpen kunnen vervangen als die er is.$$),
('bbm-12', 'bbm-12.t3', 'theorie', 3, $$Vlagvoering en jachtetiquette$$,
 $$De goede gebruiken ten opzichte van andere watersporters kennen, de verantwoording ten opzichte van het milieu, en de vlagvoering van het eigen schip.$$),
('bbm-12', 'bbm-12.t4', 'theorie', 4, $$Veiligheid$$,
 $$Kunnen uitleggen waarom voorzorgsmaatregelen aan boord nodig zijn, met benzine als brandstof in het achterhoofd. De reddingsmiddelen moeten voor onmiddellijk gebruik klaarliggen, en je kent het gebruik van zwemvest, reddingslijn en reddingsboei.$$),
('bbm-12', 'bbm-12.t5', 'theorie', 5, $$Reglementen$$,
 $$Een brede selectie uit het BPR: begripsbepalingen (schip, motorschip, groot en klein schip, snelle motorboot, waterscooter), verplichtingen van schipper en bemanning, voorzorgsmaatregelen, sturen, scheepsbescheiden, kentekens van kleine schepen, tekens van een stilliggend klein schip, geluidsseinen en noodseinen, en de vaarregels voor tegengestelde koersen, engtes, voorbijlopen, keren, hoofd- en nevenvaarwater en kruisende koersen. Ook weten dat voor bepaalde schepen een Klein Vaarbewijs verplicht is. De volledige artikelopsomming staat in het handboek.$$),

-- ---------------- Buitenboordmotor III — praktijk
('bbm-3', 'bbm-3.p1',  'praktijk',  1, $$Het schip vaarklaar maken en klaarmaken voor de nacht$$,
 $$Motor juist aanbrengen, slangen goed gebruiken, zorgvuldig vullen met voorzorgen tegen morsen, reservebrandstof goed stouwen. Motor en eventueel roer borgen, inventaris en verlichting controleren, en op de juiste manier ontluchten en ventileren.$$),
('bbm-3', 'bbm-3.p2',  'praktijk',  2, $$Vaartechnieken: koersen varen, afstoppen, gaande houden, noodstop maken$$,
 $$Gestrekte koers met de schroefwerking (wieleffect) erin verrekend, en bij zijwind zo opsturen dat de koers recht blijft. Afstoppen op motorvermogen. Gaande houden: in wind en stroom op dezelfde plaats blijven zonder dat de boeg wegdraait. Noodstop: gas terug en de motor omdraaien en weer gas geven, of gas terug en in de achteruit — zonder dat het schip door de schroefwerking dwars valt.$$),
('bbm-3', 'bbm-3.p3',  'praktijk',  3, $$Afvaren en aankomen bij hoger- en lagerwal$$,
 $$Aan beide wallen, met goed gebruik van trossen en springen. Ook aan een zachte, ondiepe wal: op tijd de motor optillen bij aankomst, en bij het afvaren eerst het achterschip afduwen.$$),
('bbm-3', 'bbm-3.p4',  'praktijk',  4, $$Man over boord manoeuvre$$,
 $$"Zwem" roepen en iemand laten wijzen in de richting van de drenkeling. De boot aan de loefzijde van de drenkeling tot stilstand brengen en de schroef van hem wegdraaien.$$),
('bbm-3', 'bbm-3.p5',  'praktijk',  5, $$Ankeren en anker op gaan$$,
 $$Een ankermanoeuvre uitvoeren zonder dat het anker onklaar raakt, met genoeg lijn gestoken zodat het zich kan ingraven. Bij het overboord zetten moet het schip langzaam deinzen.$$),
('bbm-3', 'bbm-3.p6',  'praktijk',  6, $$Bijzondere verrichtingen$$,
 $$Achteruit manoeuvreren in een box of tussen twee obstakels door, en zowel voor- als achteruit een acht en een slalom om een aantal boeien varen.$$),
('bbm-3', 'bbm-3.p7',  'praktijk',  7, $$Loskomen van aan de grond$$,
 $$Loskomen door het gewicht van de opvarenden te verplaatsen, met het juiste gebruik van de motor — en weten wanneer je assistentie moet vragen.$$),
('bbm-3', 'bbm-3.p8',  'praktijk',  8, $$Passeren van bruggen en/of sluizen$$,
 $$Een brug of sluis op de juiste wijze benaderen en de juiste seinen geven. Moet je vastmaken, dan op de juiste plaats en manier; in een sluis de boot beleggen met dubbelgenomen lijnen en die op de hand laten slippen.$$),
('bbm-3', 'bbm-3.p9',  'praktijk',  9, $$Aanvarings- en achtergrondpeiling$$,
 $$Met een achtergrondspeiling vaststellen of er gevaar voor aanvaring bestaat.$$),
('bbm-3', 'bbm-3.p10', 'praktijk', 10, $$Toepassing reglementen$$,
 $$De regels uit het BPR toepassen voor zover ze op dit type schip van toepassing zijn.$$),
('bbm-3', 'bbm-3.p11', 'praktijk', 11, $$Langszij een varend schip komen en vastmaken$$,
 $$Eerst dezelfde snelheid gaan varen en dan naar het schip toe sturen, waarbij je de zuiging opvangt. Een tweede man brengt de lijn over: eerst de voortros beleggen, dan een achterspring, dan de achtertros.$$),
('bbm-3', 'bbm-3.p12', 'praktijk', 12, $$Slepen en gesleept worden$$,
 $$Een sleeplijn overbrengen of aannemen en bevestigen, en verschillende sleepwijzen toepassen: op één sleeptros, op twee gekruiste trossen en langszij. Weten dat een rubberboot vooruit slepen heel moeilijk is.$$),
('bbm-3', 'bbm-3.p13', 'praktijk', 13, $$Een tocht in het donker$$,
 $$Varen in een periode waarin de scheepslichten ontstoken moeten zijn, en daarbij de lichten van andere vaartuigen, boeien en haveningangen herkennen en ernaar handelen.$$),
('bbm-3', 'bbm-3.p14', 'praktijk', 14, $$Eenvoudige reparaties aan de motor$$,
 $$Bougie schoonmaken en afstellen, breekpen vervangen, brandstofleiding controleren en koelwaterproblemen oplossen.$$),

-- ---------------- Buitenboordmotor III — theorie
('bbm-3', 'bbm-3.t1',  'theorie',  1, $$Terminologie$$,
 $$De belangrijkste onderdelen van het schip (als bij Buitenboordmotor I/II) en van de motor met hun functie: bougie, brandstofleiding, koelwateruitlaat, breekpen, gas- en chokehandel, startkoord.$$),
('bbm-3', 'bbm-3.t2',  'theorie',  2, $$Veiligheids- en reddingsmiddelen$$,
 $$Het gebruik kennen van drijfhulpmiddel of reddingvest, reddingsboei met reddingslijn, reddingsklos met drijvende lijn en dergelijke.$$),
('bbm-3', 'bbm-3.t3',  'theorie',  3, $$Handelen bij averij$$,
 $$De schade kunnen vaststellen en het schip op zeewaardigheid beoordelen, noodvoorzieningen treffen bij lekkage, en weten welke gegevens je bij een aanvaring opneemt.$$),
('bbm-3', 'bbm-3.t4',  'theorie',  4, $$Eenvoudige EHBO$$,
 $$Overweg kunnen met een eenvoudige verbanddoos en eerste hulp verlenen bij eenvoudige verwondingen. Onderkoeling herkennen en weten hoe te handelen.$$),
('bbm-3', 'bbm-3.t5',  'theorie',  5, $$Reglementen$$,
 $$De BPR-lijst van Buitenboordmotor I/II, uitgebreid met de geluidsseinen van bijlage 6A en een flinke reeks verkeerstekens uit bijlage 7 — verboden en geboden, doorvaartopeningen, en de optische tekens bij vaste en beweegbare bruggen en bij sluizen. Ook weten dat voor bepaalde schepen een Klein Vaarbewijs verplicht is. De volledige opsomming staat in het handboek.$$),
('bbm-3', 'bbm-3.t6',  'theorie',  6, $$Betonning en bebakening$$,
 $$De betonning van het thuiswater kennen: in ieder geval de rode stompe en de groene spitse tonnen, en de scheidingstonnen die in dat vaarwater voorkomen.$$),
('bbm-3', 'bbm-3.t7',  'theorie',  7, $$Krachten op het schip en hun gevolgen$$,
 $$Weten wat scherpe bochten bij hoge snelheid betekenen voor schip en bemanning.$$),
('bbm-3', 'bbm-3.t8',  'theorie',  8, $$Jachtetiquette en vlagvoering$$,
 $$Het voeren van vlaggen en wimpels voor motorschepen, de gebruiken aan boord, en de goede gebruiken ten opzichte van medewatersporters en anderen.$$),
('bbm-3', 'bbm-3.t9',  'theorie',  9, $$Weersinvloeden$$,
 $$Aan veranderende wolkenpatronen een weersvoorspelling kunnen doen, de betekenis van stormwaarschuwingen kennen, en de schaal van Beaufort kennen.$$),
('bbm-3', 'bbm-3.t10', 'theorie', 10, $$Gebruik van almanak en waterkaarten$$,
 $$Almanakken en waterkaarten kunnen gebruiken voor navigatie, en daarin de relevante informatie over het te bevaren gebied opzoeken en toepassen.$$)

) as v(diploma, code, kind, position, title, detail)
join diplomas dp on dp.code = v.diploma
on conflict (code) do update set
  diploma_id = excluded.diploma_id,
  kind       = excluded.kind,
  position   = excluded.position,
  title      = excluded.title,
  detail     = excluded.detail;

-- ---------------------------------------------------------------- sloep/motorvlet
--
-- Het handboek Sloep- en motorvletvaren zet de eisen niet per niveau onder
-- elkaar, maar in één matrix met een kolom per niveau. Die kolommen zijn in de
-- PDF niet betrouwbaar uit te lezen, dus staat hieronder bij alle vier de
-- niveaus dezelfde volledige lijst. Dat is bewust de ruime kant: een eis die
-- er niet bij hoort zie je staan en haal je weg, een eis die ontbreekt zie je
-- nooit. Loop de lijst één keer met het handboek naast je na — zie
-- docs/EISEN.md.

insert into requirements (diploma_id, code, kind, position, title, detail)
select dp.id, dp.code || '.' || v.suffix, v.kind::requirement_kind, v.position, v.title, v.detail
from diplomas dp
cross join (values
  ('p1',  'praktijk',  1, $$Vaarklaar maken en controleren van het schip$$,        $$Het schip en basale zaken$$),
  ('p2',  'praktijk',  2, $$Verzorgen van de waterdichtheid van het schip$$,       $$Het schip en basale zaken$$),
  ('p3',  'praktijk',  3, $$Aan dek werken$$,                                      $$Het schip en basale zaken$$),
  ('p4',  'praktijk',  4, $$Behandeling lijnen en schiemannen$$,                   $$Het schip en basale zaken$$),
  ('p5',  'praktijk',  5, $$Bedienen van de motor$$,                               $$Het schip en basale zaken$$),
  ('p6',  'praktijk',  6, $$Zorg voor de motor en motorkamer$$,                    $$Het schip en basale zaken$$),
  ('p7',  'praktijk',  7, $$Communiceren$$,                                        $$Het schip en basale zaken$$),
  ('p8',  'praktijk',  8, $$Sturen$$,                                              $$Manoeuvreren$$),
  ('p9',  'praktijk',  9, $$Manoeuvreren$$,                                        $$Manoeuvreren$$),
  ('p10', 'praktijk', 10, $$Afvaren van een hogerwal en langswal steiger$$,        $$Havenmanoeuvres$$),
  ('p11', 'praktijk', 11, $$Aankomen aan een hogerwal en langswal steiger$$,       $$Havenmanoeuvres$$),
  ('p12', 'praktijk', 12, $$Afvaren van een hogerwal en lagerwal box$$,            $$Havenmanoeuvres$$),
  ('p13', 'praktijk', 13, $$Aankomen in een hogerwal en lagerwal box$$,            $$Havenmanoeuvres$$),
  ('p14', 'praktijk', 14, $$Afvaren van een lagerwal steiger$$,                    $$Havenmanoeuvres$$),
  ('p15', 'praktijk', 15, $$Aankomen aan een lagerwal steiger$$,                   $$Havenmanoeuvres$$),
  ('p16', 'praktijk', 16, $$Afvaren uit een box met dwarswind$$,                   $$Havenmanoeuvres$$),
  ('p17', 'praktijk', 17, $$Aankomen in een box met dwarswind$$,                   $$Havenmanoeuvres$$),
  ('p18', 'praktijk', 18, $$Afmeren$$,                                             $$Havenmanoeuvres$$),
  ('p19', 'praktijk', 19, $$Gebruik van kaart en almanak$$,                        $$Navigatie$$),
  ('p20', 'praktijk', 20, $$Gebruik navigatie-instrumenten$$,                      $$Navigatie$$),
  ('p21', 'praktijk', 21, $$Navigeren aan boord$$,                                 $$Navigatie$$),
  ('p22', 'praktijk', 22, $$Tochtvoorbereiding en het aanlopen van havens$$,       $$Tochtvaren$$),
  ('p23', 'praktijk', 23, $$Passeren van sluizen en bruggen$$,                     $$Tochtvaren$$),
  ('p24', 'praktijk', 24, $$Toepassen van de reglementen$$,                        $$Tochtvaren$$),
  ('p25', 'praktijk', 25, $$Nachtvaren$$,                                          $$Tochtvaren — in het handboek pas vanaf Schipper (CWO III)$$),
  ('p26', 'praktijk', 26, $$Gebruik van de veiligheidsuitrusting en reddingsmiddelen aan boord$$, $$Noodsituaties$$),
  ('p27', 'praktijk', 27, $$Man over boord$$,                                      $$Noodsituaties$$),
  ('p28', 'praktijk', 28, $$Slepen en gesleept worden$$,                           $$Noodsituaties — hiervoor bestaat een aparte module; verplicht voor All Round Schipper$$),
  ('p29', 'praktijk', 29, $$Loskomen van aan de grond$$,                           $$Noodsituaties$$),
  ('p30', 'praktijk', 30, $$Verhelpen van storingen$$,                             $$Noodsituaties$$),
  ('p31', 'praktijk', 31, $$EHBO$$,                                                $$Noodsituaties$$),
  ('p32', 'praktijk', 32, $$Ankeren$$,                                             $$Overig$$),
  ('p33', 'praktijk', 33, $$Vaar- en jachtetiquette en zorg voor het schip$$,      $$Overig$$),
  ('t1',  'theorie',   1, $$Scheeps- en motortermen$$,                             null),
  ('t2',  'theorie',   2, $$Werking van de motor$$,                                null),
  ('t3',  'theorie',   3, $$Theoretische beginselen van het manoeuvreren op de motor$$, null),
  ('t4',  'theorie',   4, $$Theorie van alle genoemde praktijkmanoeuvres$$,        null),
  ('t5',  'theorie',   5, $$Reglementen$$,                                         null),
  ('t6',  'theorie',   6, $$Klein Vaarbewijs$$,
   $$Kennis van KVB I vanaf Schipper (CWO III); voor All Round Schipper (CWO IV) is het certificaat zelf vereist. Een Klein Vaarbewijs geeft vrijstelling van het theorie-examen.$$)
) as v(suffix, kind, position, title, detail)
where dp.code in ('sloep-1', 'sloep-2', 'sloep-3', 'sloep-4')
on conflict (code) do update set
  diploma_id = excluded.diploma_id,
  kind       = excluded.kind,
  position   = excluded.position,
  title      = excluded.title,
  detail     = excluded.detail;

-- ---------------------------------------------------------------- onderdelen
--
-- Eisen waar het handboek een opsomming achter zet: knopen, commando's,
-- termen, onderdelen van de boot. Die worden hier losse regels onder hun eis,
-- zodat een instructeur kan bijhouden dat de paalsteek zit en de mastworp nog
-- niet. Ze tellen niet mee in de voortgang — zie 012-onderdelen.sql.
--
-- De code van een onderdeel is die van zijn eis plus het nummer, dus
-- roeien-12.t1.3 is de derde knoop van Schiemanswerk bij Roeien I/II. Opnieuw
-- draaien werkt bij op die code, net als bij de eisen zelf.
--
-- Bewust níét uitgesplitst: de artikellijsten uit het Binnenvaartpolitie-
-- reglement. Vanaf Roeien III en Kielboot III zijn dat er tientallen, en een
-- scherm met tachtig vinkjes helpt niemand op een steiger. Die blijven één eis.

insert into requirements (diploma_id, parent_id, code, kind, position, title)
select p.diploma_id, p.id, p.code || '.' || v.position, p.kind, v.position, v.title
from (values

-- ---- Roeien I/II
('roeien-12.t1',  1, $$Twee halve steken, de eerste slippend$$),
('roeien-12.t1',  2, $$Achtknoop$$),
('roeien-12.t1',  3, $$Platte knoop$$),
('roeien-12.t1',  4, $$Mastworp, met slipsteek als borg$$),
('roeien-12.t1',  5, $$Een lijn opschieten$$),
('roeien-12.t1',  6, $$Een lijn beleggen op een kikker$$),

('roeien-12.p3',  1, $$Dollen ... in$$),
('roeien-12.p3',  2, $$Los ... voor en los ... achter$$),
('roeien-12.p3',  3, $$Op ... riemen$$),
('roeien-12.p3',  4, $$Haalt op ... gelijk$$),
('roeien-12.p3',  5, $$Stopt ... af$$),
('roeien-12.p3',  6, $$Strijkt ... gelijk$$),
('roeien-12.p3',  7, $$Zet ... af$$),
('roeien-12.p3',  8, $$Riemen ... lopen$$),
('roeien-12.p3',  9, $$Riemen ... geroeid$$),

('roeien-12.t2',  1, $$Slagroeier$$),
('roeien-12.t2',  2, $$Boegroeier$$),
('roeien-12.t2',  3, $$Midroeier$$),
('roeien-12.t2',  4, $$Roerganger$$),
('roeien-12.t2',  5, $$Haakvoor$$),
('roeien-12.t2',  6, $$Stuurboord en bakboord$$),
('roeien-12.t2',  7, $$Hogerwal en lagerwal$$),
('roeien-12.t2',  8, $$Bomen$$),
('roeien-12.t2',  9, $$Jagen$$),
('roeien-12.t2', 10, $$Wrikken$$),
('roeien-12.t2', 11, $$In de wind$$),
('roeien-12.t2', 12, $$Opschieten$$),
('roeien-12.t2', 13, $$Beleggen$$),

('roeien-12.t3',  1, $$Boeg$$),
('roeien-12.t3',  2, $$Hek$$),
('roeien-12.t3',  3, $$Dolboord$$),
('roeien-12.t3',  4, $$Doften$$),
('roeien-12.t3',  5, $$Roer$$),
('roeien-12.t3',  6, $$Helmstok$$),
('roeien-12.t3',  7, $$Stuurboord en bakboord$$),
('roeien-12.t3',  8, $$Roeiriem$$),
('roeien-12.t3',  9, $$Wrikriem$$),

-- ---- Roeien III
('roeien-3.p3',   1, $$Riemen ... op$$),
('roeien-3.p3',   2, $$Dollen ... in$$),
('roeien-3.p3',   3, $$Dollen ... richten$$),
('roeien-3.p3',   4, $$Riemen ... toe$$),
('roeien-3.p3',   5, $$Los ... voor en los ... achter$$),
('roeien-3.p3',   6, $$Op ... riemen$$),
('roeien-3.p3',   7, $$Haalt op ... gelijk$$),
('roeien-3.p3',   8, $$Stopt ... af$$),
('roeien-3.p3',   9, $$Strijkt ... gelijk$$),
('roeien-3.p3',  10, $$Zet ... af$$),
('roeien-3.p3',  11, $$Riemen ... lopen$$),
('roeien-3.p3',  12, $$Riemen ... over$$),
('roeien-3.p3',  13, $$Riemen ... geroeid$$),
('roeien-3.p3',  14, $$Stootwillen ... binnen of ... buiten$$),

('roeien-3.p19',  1, $$Twee halve steken, de eerste slippend$$),
('roeien-3.p19',  2, $$Achtknoop$$),
('roeien-3.p19',  3, $$Platte knoop$$),
('roeien-3.p19',  4, $$Mastworp, met slipsteek als borg$$),
('roeien-3.p19',  5, $$Schootsteek (enkel)$$),
('roeien-3.p19',  6, $$Paalsteek$$),
('roeien-3.p19',  7, $$Een lijn opschieten$$),
('roeien-3.p19',  8, $$Een lijn beleggen op een kikker$$),

('roeien-3.t1',   1, $$Twee halve steken, de eerste slippend$$),
('roeien-3.t1',   2, $$Achtknoop$$),
('roeien-3.t1',   3, $$Platte knoop$$),
('roeien-3.t1',   4, $$Mastworp, met slipsteek als borg$$),
('roeien-3.t1',   5, $$Schootsteek (enkel)$$),
('roeien-3.t1',   6, $$Paalsteek$$),
('roeien-3.t1',   7, $$Een lijn opschieten en beleggen op een kikker$$),
('roeien-3.t1',   8, $$Schavielen en de maatregelen daartegen$$),

('roeien-3.t2',   1, $$Slagroeier$$),
('roeien-3.t2',   2, $$Boegroeier$$),
('roeien-3.t2',   3, $$Roerganger$$),
('roeien-3.t2',   4, $$Haakvoor$$),
('roeien-3.t2',   5, $$Stuurboord en bakboord$$),
('roeien-3.t2',   6, $$Hogerwal en lagerwal$$),
('roeien-3.t2',   7, $$Loef en lij$$),
('roeien-3.t2',   8, $$Bomen$$),
('roeien-3.t2',   9, $$Jagen$$),
('roeien-3.t2',  10, $$Wrikken$$),
('roeien-3.t2',  11, $$In de wind$$),
('roeien-3.t2',  12, $$Opschieten$$),
('roeien-3.t2',  13, $$Beleggen$$),

('roeien-3.t3',   1, $$Boeg$$),
('roeien-3.t3',   2, $$Hek$$),
('roeien-3.t3',   3, $$Spiegel$$),
('roeien-3.t3',   4, $$Dolboord$$),
('roeien-3.t3',   5, $$Doften$$),
('roeien-3.t3',   6, $$Roer$$),
('roeien-3.t3',   7, $$Helmstok$$),
('roeien-3.t3',   8, $$Stuurboord en bakboord$$),
('roeien-3.t3',   9, $$Roeiriem$$),
('roeien-3.t3',  10, $$Wrikriem$$),
('roeien-3.t3',  11, $$Blad$$),
('roeien-3.t3',  12, $$Handvat$$),
('roeien-3.t3',  13, $$Dollen$$),
('roeien-3.t3',  14, $$Dolpot$$),
('roeien-3.t3',  15, $$Landvast$$),
('roeien-3.t3',  16, $$Hoosvat$$),

-- ---- Kielboot I
('kielboot-1.p6',  1, $$Klaar om te wenden$$),
('kielboot-1.p6',  2, $$Ree$$),
('kielboot-1.p6',  3, $$Fok bak$$),
('kielboot-1.p6',  4, $$Fok over$$),
('kielboot-1.p6',  5, $$Fok aan$$),

('kielboot-1.t1',  1, $$Achtknoop$$),
('kielboot-1.t1',  2, $$Twee halve steken, de eerste slippend$$),
('kielboot-1.t1',  3, $$Paalsteek$$),
('kielboot-1.t1',  4, $$Reefsteek (platte knoop)$$),
('kielboot-1.t1',  5, $$Beleggen op klamp, nagel of kikker$$),
('kielboot-1.t1',  6, $$Een tros opschieten$$),

('kielboot-1.t2',  1, $$Hogerwal en lagerwal$$),
('kielboot-1.t2',  2, $$Bakboord en stuurboord$$),
('kielboot-1.t2',  3, $$Hoge en lage zijde$$),
('kielboot-1.t2',  4, $$Loef- en lijzijde$$),
('kielboot-1.t2',  5, $$In de wind$$),
('kielboot-1.t2',  6, $$Aan de wind$$),
('kielboot-1.t2',  7, $$Halve wind$$),
('kielboot-1.t2',  8, $$Ruime wind$$),
('kielboot-1.t2',  9, $$Voor de wind$$),
('kielboot-1.t2', 10, $$Oploeven$$),
('kielboot-1.t2', 11, $$Afvallen$$),
('kielboot-1.t2', 12, $$Overstag gaan$$),
('kielboot-1.t2', 13, $$Gijpen$$),
('kielboot-1.t2', 14, $$Kruisrak$$),
('kielboot-1.t2', 15, $$Killen van het zeil$$),

-- ---- Kielboot II
('kielboot-2.p6',  1, $$Klaar om te wenden$$),
('kielboot-2.p6',  2, $$Ree$$),
('kielboot-2.p6',  3, $$Fok bak$$),
('kielboot-2.p6',  4, $$Fok over$$),
('kielboot-2.p6',  5, $$Fok aan$$),

('kielboot-2.t1',  1, $$Twee halve steken, de eerste slippend$$),
('kielboot-2.t1',  2, $$Achtknoop$$),
('kielboot-2.t1',  3, $$Paalsteek$$),
('kielboot-2.t1',  4, $$Platte knoop$$),
('kielboot-2.t1',  5, $$Mastworp, met slipsteek als borg$$),
('kielboot-2.t1',  6, $$Schootsteek (enkel)$$),
('kielboot-2.t1',  7, $$Een lijn opschieten$$),
('kielboot-2.t1',  8, $$Beleggen op een kikker$$),

('kielboot-2.t2',  1, $$De zeiltermen van Kielboot I$$),
('kielboot-2.t2',  2, $$Deinzen$$),
('kielboot-2.t2',  3, $$Opschieten$$),
('kielboot-2.t2',  4, $$Beleggen$$),

('kielboot-2.t3',  1, $$Blok$$),
('kielboot-2.t3',  2, $$Landvast$$),
('kielboot-2.t3',  3, $$Kiel$$),
('kielboot-2.t3',  4, $$Helmstok$$),
('kielboot-2.t3',  5, $$Roer$$),
('kielboot-2.t3',  6, $$Mast$$),
('kielboot-2.t3',  7, $$Giek$$),
('kielboot-2.t3',  8, $$Val$$),
('kielboot-2.t3',  9, $$Schoot$$),
('kielboot-2.t3', 10, $$Halshoek$$),
('kielboot-2.t3', 11, $$Schoothoek$$),
('kielboot-2.t3', 12, $$Grootzeil$$),
('kielboot-2.t3', 13, $$Fok$$),

-- ---- Kielboot III
('kielboot-3.p18', 1, $$Twee halve steken$$),
('kielboot-3.p18', 2, $$Slipsteek$$),
('kielboot-3.p18', 3, $$Achtknoop$$),
('kielboot-3.p18', 4, $$Platte knoop$$),
('kielboot-3.p18', 5, $$Schootsteek, enkel en dubbel$$),
('kielboot-3.p18', 6, $$Mastworp, op twee manieren$$),
('kielboot-3.p18', 7, $$Paalsteek$$),
('kielboot-3.p18', 8, $$Een tros opschieten$$),
('kielboot-3.p18', 9, $$Tros beleggen op een bolder$$),
('kielboot-3.p18', 10, $$Lijn beleggen op een klamp of nagel$$),

('kielboot-3.t1',  1, $$Twee halve steken, de eerste slippend$$),
('kielboot-3.t1',  2, $$Achtknoop$$),
('kielboot-3.t1',  3, $$Paalsteek$$),
('kielboot-3.t1',  4, $$Platte knoop$$),
('kielboot-3.t1',  5, $$Mastworp, op twee manieren$$),
('kielboot-3.t1',  6, $$Schootsteek, enkel en dubbel$$),
('kielboot-3.t1',  7, $$Opschieten en beleggen, op kikker en bolder$$),
('kielboot-3.t1',  8, $$Verschil tussen geslagen en gevlochten touwwerk$$),
('kielboot-3.t1',  9, $$Welk touw waarvoor: landvast, val, schoot, sleeplijn, ankerlijn$$),
('kielboot-3.t1', 10, $$Schavielen en de maatregelen daartegen$$),

('kielboot-3.t2',  1, $$De zeiltermen van Kielboot II$$),
('kielboot-3.t2',  2, $$Bovenlangs en onderlangs$$),
('kielboot-3.t2',  3, $$Dwarspeiling$$),
('kielboot-3.t2',  4, $$Bezeild$$),
('kielboot-3.t2',  5, $$Binnen de wind$$),
('kielboot-3.t2',  6, $$Korte slag en lange slag$$),
('kielboot-3.t2',  7, $$Opschieter$$),
('kielboot-3.t2',  8, $$Zuigen en duiken$$),
('kielboot-3.t2',  9, $$Planeren$$),
('kielboot-3.t2', 10, $$Volvallen$$),
('kielboot-3.t2', 11, $$Verhalen$$),
('kielboot-3.t2', 12, $$Verlijeren en drift$$),
('kielboot-3.t2', 13, $$Bijliggen$$),
('kielboot-3.t2', 14, $$Bakhouden$$),

('kielboot-3.t3',  1, $$Voorsteven$$),
('kielboot-3.t3',  2, $$Spiegel$$),
('kielboot-3.t3',  3, $$Sluiting en kous$$),
('kielboot-3.t3',  4, $$Blok$$),
('kielboot-3.t3',  5, $$Stootkussen$$),
('kielboot-3.t3',  6, $$Hoosvat$$),
('kielboot-3.t3',  7, $$Landvast$$),
('kielboot-3.t3',  8, $$Kiel$$),
('kielboot-3.t3',  9, $$Helmstok$$),
('kielboot-3.t3', 10, $$Roer en roerblad$$),
('kielboot-3.t3', 11, $$Mast$$),
('kielboot-3.t3', 12, $$Giek$$),
('kielboot-3.t3', 13, $$Val$$),
('kielboot-3.t3', 14, $$Halstalie$$),
('kielboot-3.t3', 15, $$Schoot$$),
('kielboot-3.t3', 16, $$Voorlijk, achterlijk en onderlijk$$),
('kielboot-3.t3', 17, $$Halshoek en schoothoek$$),
('kielboot-3.t3', 18, $$Grootzeil$$),
('kielboot-3.t3', 19, $$Fok$$),

-- ---- Kielboot IV
('kielboot-4.p20', 1, $$De knopen en steken van Kielboot III$$),
('kielboot-4.p20', 2, $$Splits in driestrengs touwwerk$$),
('kielboot-4.p20', 3, $$Benaaide takeling$$),

('kielboot-4.t11', 1, $$Schacht$$),
('kielboot-4.t11', 2, $$Stok$$),
('kielboot-4.t11', 3, $$Kruis$$),
('kielboot-4.t11', 4, $$Armen en vloeien$$),
('kielboot-4.t11', 5, $$Verschil lichtgewicht- en volgewichtanker$$),
('kielboot-4.t11', 6, $$Hollands stokanker$$),
('kielboot-4.t11', 7, $$Dreg en klapdreg$$),
('kielboot-4.t11', 8, $$Danforth-anker$$),
('kielboot-4.t11', 9, $$Ploegschaaranker$$),

-- ---- Buitenboordmotor I/II
('bbm-12.p15', 1, $$Platte knoop$$),
('bbm-12.p15', 2, $$Paalsteek$$),
('bbm-12.p15', 3, $$Halve steek$$),
('bbm-12.p15', 4, $$Mastworp$$),
('bbm-12.p15', 5, $$Een lijn opschieten$$),
('bbm-12.p15', 6, $$Beleggen op een kikker of bolder$$),

('bbm-12.t1',  1, $$Boeg$$),
('bbm-12.t1',  2, $$Stuurboord en bakboord$$),
('bbm-12.t1',  3, $$Steven$$),
('bbm-12.t1',  4, $$Spanten$$),
('bbm-12.t1',  5, $$Spiegel$$),
('bbm-12.t1',  6, $$Motorsteun$$),
('bbm-12.t1',  7, $$Vrijboord$$),
('bbm-12.t1',  8, $$Bougie$$),
('bbm-12.t1',  9, $$Brandstofslang$$),
('bbm-12.t1', 10, $$Carburator$$),
('bbm-12.t1', 11, $$Koelwateruitlaat$$),
('bbm-12.t1', 12, $$Gas- en chokehandel$$),

-- ---- Buitenboordmotor III
('bbm-3.t1',   1, $$De onderdelen van Buitenboordmotor I/II$$),
('bbm-3.t1',   2, $$Bougie$$),
('bbm-3.t1',   3, $$Brandstofleiding$$),
('bbm-3.t1',   4, $$Koelwateruitlaat$$),
('bbm-3.t1',   5, $$Breekpen$$),
('bbm-3.t1',   6, $$Gas- en chokehandel$$),
('bbm-3.t1',   7, $$Startkoord$$),

('bbm-3.p14',  1, $$Bougie schoonmaken en afstellen$$),
('bbm-3.p14',  2, $$Breekpen vervangen$$),
('bbm-3.p14',  3, $$Brandstofleiding controleren$$),
('bbm-3.p14',  4, $$Koelwaterproblemen oplossen$$)

) as v(parent, position, title)
join requirements p on p.code = v.parent
on conflict (code) do update set
  diploma_id = excluded.diploma_id,
  parent_id  = excluded.parent_id,
  kind       = excluded.kind,
  position   = excluded.position,
  title      = excluded.title;
